### ISSUE TITLE
Q method error

### ISSUE THREAD

**Issue by andr0s** [hmarr/mongoengine#103]
Branch 0.4.

1) ParsedSite.objects.get( Q(site=parsed_query1) | Q(site=parsed_query2) )
2) ParsedSite.objects.filter( site=parsed_query1) or ParsedSite.objects.filter(site=parsed_query2)

There's only one parsed_query matching, parsed_query2. ParsedSite object with site equals to parsed_query1 doesn't exist.

First case (1) produces "ParsedSite matching query does not exist" error.
Second case (2) works correctly and finds ParsedSite object with site=parsed_query2.

Sorry for bad English.

**Comment by iapain** [comment]
Couldn't repeat this problem. Added a test case in queryset test suite. See #104

**Comment by ghost** [comment]
have similar problem /branch 0.4/:

<pre>
In [25]: Profile.objects(Q(want_to__movie=True) & Q(want_to__walk=True))
Out[25]: [&lt;ProfileNG: ProfileNG object>]

In [26]: Profile.objects(Q(want_to__movie=True) | Q(want_to__walk=True))
Out[26]: []
</pre>

Profile.want_to is a DictField. Second query should return at least one result

**Comment by andr0s** [comment]
Yep. It looks like the same problem that I told about.

**Comment by iapain** [comment]
Testcase does not test dict field. It needs to be validated.

**Comment by ghost** [comment]
My mistake! I was connected to old mongodb server which doesn't support $or queries (1.4). After upgrade to 1.6.5 everything seems to be ok.
I think it should be mentioned in Q object docs (mongo 1.5.3+ required)

**Comment by hmarr** [comment]
Apologies for the delay. I'll add the requirement to the docs - cheers!
