### ISSUE TITLE
Migration Support

### ISSUE THREAD

**Issue by matthewphiong** [hmarr/mongoengine#105]
As some point there might be a need to add a new field(s) to the the documents we have defined. Currently there is no migration support available and the only way I can think of is to add the field(s) manually to MongoDB.

Hope to see this feature in the future release of MongoEngine.

**Comment by sgtpep** [comment]
+1

**Comment by iapain** [comment]
-1 MongoDB is schemaless, you can add new fields to MongoEngine Models and it'll reflects in your new documents and if field is absent you'll get `NULL`

**Comment by rozza** [comment]
Closing thanks to iapain for clarifying its inherent in MongoDB and mongoengine can already handle that use case :)

**Comment by sergio-bershadsky** [comment]
But, sometimes we need to migrate some data (ex. south datamigration) or delete unused field (ODM will raise error if model contains unknown field) or rename field whithout migrations it'll be able only with hands from shell.

**Comment by MacMaru** [comment]
A pattern that has worked for us:

EDIT:  this gave us mixed results: use <Document>._data to get your db-representation of stuff and take it from there
- create a `migrate_<foo>.py` file that imports the new version of your document(s)
- create a stub to the old version of the document that exposes the fields you need for your migration

Now you can access/filter on old documents and leverage mongoengine's dereferencing.

Example:
Suppose you have cars that were owned by organizations, but now want them to be owned by the organizations` owners.

That can go along the lines of:

``` python
from mongoengine import Document, ReferenceField
from .models import Car, Organization


class _Car( Document ): 
    '''
    A stub for our previous Car Document.
    It references the same collection as our new Car Document,
    but defines some fields we need from the old document.
    '''

    # Reference the 'car' collection, verify that you use the correct collection name
    meta = { 'collection': 'car' }

    # We only need the `owner` field and can ignore other fields here since 
    # we're not(!) going to save these old car Documents.
    owner = ReferenceField( 'Organization' )


class Migrator( object ):
    '''
    Defines migration functions.
    '''
    def migrate_cars( self ):
        # Previously, cars had an owner that was an `Organization`.
        # Now cars have an owner that is a `Person`. 
        # We want to migrate the new Car owner to be the Organization's owner.

        for car in Car.objects:
            car.owner = _Car.objects.get( id=car.id ).owner.person 
            car.save( cascade=False )
```

**Comment by MacMaru** [comment]
@rozza, 

This is magik!

It seems `_Car.objects` returns `Car` instances, whose owners are `Organizations`, although they're defined as `Persons` on the `Car` class...

So the following works:

``` python
for car in _Car.objects:
    car.owner = car.owner.person
    car.save()

    assert isinstance( car.owner, Person )

```

**Comment by MacMaru** [comment]
Above gave us mixed results: use `Document._data[<field>]` to get your db-representation of stuff and taking it from there worked very nicely.

**Comment by serpulga** [comment]
Adding a required field to a Document, causes `ValidationError` to be raised when calling `save` upon 'old' Documents. Even though MongoDB is schema-less, MongoEngine validation also introduces the need for a migration tool.
