### ISSUE TITLE
Add multiple database support

### ISSUE THREAD

**Issue by hmarr** [hmarr/mongoengine#11]
At the moment, only one database connection may be used. MongoDB supports master-slave replication and replica pairs (plus auto-sharding, which is in alpha, and limited master-master replication) - MongoEngine should provide an interface to working with these setups.

**Comment by yashh** [comment]
Sayadn's http://github.com/sayadn/mongoengine fork has support for multi databases. Although his approach is right, more flexibility should be given to the user to specify collection name for each database. 

Also mongoengine.connect should n't be in settings.py. Settings should clearly be place to specify your settings rather than making a connection.

**Comment by joshourisman** [comment]
I've also implemented the very, very beginnings of this sort of thing in my fork; although my purposes were solely for being able to use a different database when running tests and it's a bit of a hack right now. You can see what I did here: http://github.com/joshourisman/mongoengine/commit/d5fe9c17fae40e4fb1b79e9bbc0f8e0490748485

**Comment by nbyloff** [comment]
I was looking at using mongodb and mysql together in a django project. With mongoengine current setup, it's not really feasible. This project here: https://github.com/django-mongodb-engine/mongodb-engine

Allows for DB configurations in the settings.py of Django like this:

DATABASES = {
    'default': {
        'ENGINE': 'django_mongodb_engine',
        'NAME': 'test',
        'USER': '',
        'PASSWORD': '',
        'HOST': 'localhost',
        'PORT': 27017,
    }
}

I think this would be a great feature in mongoengine so multiple DB's (like mysql & mongodb) can work together in the same django app

**Comment by joshourisman** [comment]
It's entirely possible and feasible to use both mongoengine and the Django ORM at the same time. Mongoengine is not used through Django's ORM, so there's no conflict with setting it up and also setting up mysql.

**Comment by nbyloff** [comment]
Yeah, I figured I was trying to make it more complicated than it really is. Just used to the way you define connections in Django, and it felt cleaner to allow the connection to be made in the Django DATABASES property. I will continue to make both connections the way I do now.

**Comment by bbelchak** [comment]
I think a simple approach to this would be to accept a PyMongo Connection object as one of the parameters, and then the developer can decide which type of Connection class they would like to use (i.e. MasterSlaveConnection)

**Comment by rozza** [comment]
Hi should have closed this was added in e80144e9f2399814760a343ee1c34a4e3e785c26 and is currently in the dev branch..

**Comment by anujacharya1** [comment]
Is there any documentation on how to achieve the multiple db using sql and mongo
