### ISSUE TITLE
Failing test "Ensure that Q objects may be used to query for documents"

### ISSUE THREAD

**Issue by nvie** [hmarr/mongoengine#110]
Hi Harry,

When checked out the latest HEAD, I get the following error when running the test suite:
    ======================================================================
    FAIL: Ensure that Q objects may be used to query for documents.
    ----------------------------------------------------------------------
    Traceback (most recent call last):
      File "/home/nvie/mongoengine/tests/queryset.py", line 528, in test_q
        self.assertTrue(all(obj.id in posts for obj in published_posts))
    AssertionError

```
----------------------------------------------------------------------
Ran 102 tests in 1.420s
```

Cheers,
Vincent

**Comment by hmarr** [comment]
Hey,

I'm not getting the failure locally (either on master or dev), which version of PyMongo and MongoDB are you using?

Cheers,
Harry

**Comment by nvie** [comment]
I'm using MongoDB v1.4.4 and pymongo 1.9 on Ubuntu 10.10.

On another system I also don't get the error. That system has MongoDB v1.6.4 and pymongo 1.9 on Ubuntu 10.04.

So it's probably related to the MongoDB version that's a bit behind (1.4). I'll upgrade and check again. You might want to check it out if you aim at being 1.4 compatible.

**Comment by nvie** [comment]
I can confirm that all tests pass with MongoDB v1.6.4.

**Comment by rozza** [comment]
Closing issue
