### ISSUE TITLE
ListField Memory probs

### ISSUE THREAD

**Issue by jassinm** [hmarr/mongoengine#114]
running a simple loop on a document having a Listfield(Referencefile) as field:

for doc in Doc.objects():
    for doc.referencedoc:
         .......

the listfield has about 500 elements.

the process memory increases to 10GB after 120 elements

some early print of heapy

 Index  Count   %     Size   % Cumulative  % Kind (class / dict of class)
     0  23878   7 10332304  23  10332304  23 dict (no owner)
     1 123423  36  8179848  18  18512152  41 str
     2  23600   7  6608000  14  25120152  55 dict of bson.objectid.ObjectId
     3  19537   6  5470360  12  30590512  67 dict of bson.dbref.DBRef
     4  35925  11  3131744   7  33722256  74 unicode
     5  17765   5  1546280   3  35268536  77 tuple
     6  23600   7  1510400   3  36778936  81 bson.objectid.ObjectId
     7   8439   2  1481848   3  38260784  84 list
     8  19537   6  1250368   3  39511152  87 bson.dbref.DBRef
     9   3856   1  1079680   2  40590832  89 dict of 0x103095ac0

**Comment by jassinm** [comment]
doing this solves the prob :

for doc in Doc.objects():
   while doc.referencedoc:
        docref=doc.referencedoc.pop()

Why keep All in memory?

**Comment by rozza** [comment]
Hi, is there an action to be taken in this ticket ?  Or is it ok to close it?

**Comment by rozza** [comment]
Closing - no action.
