### ISSUE TITLE
Possibility to bypass class_name check in queryset

### ISSUE THREAD

**Issue by lig** [hmarr/mongoengine#115]
I think it might be helpful to be able to bypass "self._initial_query = {'_types': self._document._class_name}" restriction in QuerySet constructor not only when allow_inheritance is disabled but for any query i need.

E.g. for class SecondDocument(FirstDocument) this will let to select objects that are not yet instances of SecondDocument and modify them as they are. Or create SecondDocument instance from FirstDocument instance to enhance this particular instance.

**Comment by hmarr** [comment]
Fixed by https://github.com/hmarr/mongoengine/commit/69171282e9064153fb0b6d87b4dba2036ccc6038
