### ISSUE TITLE
Add Django integration

### ISSUE THREAD

**Issue by hmarr** [hmarr/mongoengine#12]
- If a connection has not been specified and a connection is needed, try importing the database settings from `django.conf.settings`.
- Add a Django package to MongoEngine that contains implementations of the auth (done 07/01/10), sessions (done 11/01/10), etc frameworks, using MongoEngine. This will allow Django to be used more easily without the ORM.

**Comment by aparo** [comment]
I'll have fixed some compatibilty problems with django: such as get_or_create and i'm trying to replace django orm with mongoengine one only replacing:
from django.db import models
with
from mongoengine.db import models

Next I'll try to modify mongoengine to be more integrated in django, but this will require django as dependence.

**Comment by agronholm** [comment]
Just my 2 cents as a new user -- I for one don't want to have anything to do with Django, so please don't make it a required dependency.

**Comment by hmarr** [comment]
@agronholm Don't worry, Django will never be a dependency of MongoEngine. Being completely framework agnostic is one of our core principles. This issue was talking more about adding some helpers to provide integration if Django is present. I'd ideally also like to do the same for other frameworks (in fact someone has already done some work on flask intergration at http://bitbucket.org/danjac/flask-mongoengine).
Cheers,
Harry

**Comment by hmarr** [comment]
A vague, old issue - there is already quite a bit of Django integration.

**Comment by aparo** [comment]
I and Flaper87 had integrated mongoengine in a pure django way and it's available in django-mongodb-engine on github.

**Comment by hmarr** [comment]
@aparo Yea that seems like a nice project - good work! What's the story between the django-nonrel backend and Alex Gaynor's GSoC stuff?
