### ISSUE TITLE
Add support for typed dictionaries with complex values

### ISSUE THREAD

**Issue by dhm116** [hmarr/mongoengine#120]
In the event that there is a dictionary with consistent keys and values (ideally, where the values are Documents, ReferenceFields, etc.), I don't see any reason why the DictField or some additional field type couldn't support this case.

I have a working prototype that supports keys of any valid dictionary key type along with values of types ListField, ReferenceField and any class that extends Document or EmbeddedDocument, so I know this can be done.  While I would love nothing more than to offer this back to the project, due to the constraints of the project funding this particular effort at our research lab, I cannot.

My functioning prototype extends DictField and overrides to_python and to_mongo, however I was hoping to see a more elegant solution for handling lists and references than what I came up with, which was to simply duplicate/merge certain functionality from various other Field types.

Any thoughts or suggestions?

**Comment by rozza** [comment]
Hi I think what you are after has been added in dev.

Checkout commit 32bab13a8acc0e091094468be0a6d890719bfec5

(The test cases give good use cases)

**Comment by dhm116** [comment]
Looks great! Much more elegant and simple than what I came up with!
