### ISSUE TITLE
item_frequencies doesn't work if tag is also the name of a native js function

### ISSUE THREAD

**Issue by nickvlku** [hmarr/mongoengine#122]
In my database, I have a set of tags defined in a model like so:

```
tags = ListField(StringField())
```

If I have a word that happens to also be a native javascript function, like 'watch', the following appears when I run ObjectName.objects().item_frequencies('tags'):

```
..
 u'wall': 1.0,
 u'washington': 22.0,
 u'watch': u'1function watch() {\n    [native code]\n}',
 u'water': 1.0,
 u'watertower': 1.0,
...
```

I think the problem is in queryset.py's item_frequencies.  I have a hackish solution to it (checking if the previous value in the array is a number, if not using 0), but I don't really like it.  Will play around with it some more, but wanted to put it here just so I know I'm not crazy.

Thanks!
Nick

**Comment by rozza** [comment]
Thanks @nickvlku this is now fixed in dev
