### ISSUE TITLE
use of __getitem__ override in library code

### ISSUE THREAD

**Issue by StuartMitchell** [hmarr/mongoengine#123]
Hi I have been using mongo engine for a while now and have found it a god match for our needs.

Now I have a class that inherits from document where I overload the subscript operator [] or (**setitem**, **getitem**).
This however leads to a collision with some bits of your code in document.save() where you need to use your version of document.**setitem** but instead use the subclasses.

self[id_field] = self._fields[id_field].to_python(object_id)

hence the error.

I'm not sure the best way to resolve this but I have a fork of your code where I change that line to 

document.**setitem**(self, field, self._fields[id_field].to_python(object_id))

Then you do not assume that document.**setitem** is not overriden in subclasses.

Stu

**Comment by rozza** [comment]
Can you explain more about your use case ?

Also I couldn't get the proposed fix code to work - so any more insight would be welcome :)

**Comment by rozza** [comment]
Closing due to lack of feedback / action
