### ISSUE TITLE
Connections leak using Celery

### ISSUE THREAD

**Issue by benweatherman** [hmarr/mongoengine#128]
I'm using celery to do some offline processing and my mongo connections don't ever seem to get closed. Here's a snippet of what I'm doing:

```
@periodic_task(run_every=timedelta(minutes=5))
def refresh_bookmark_counts(**kwargs):
        db = None
        try:
            connect('MyDB')
            user = User.objects..count() # Or any DB action really
        except Exception as e:
            logging.error('Exception while indexing: {0}'.format(e))
        finally:
            if db:
                db.logout()
                db.connection.end_request()
                db.connection.disconnect()
```

When I run `db.serverStatus()` after running this asynchronously with Celery, the number of connections goes up every time this runs.

My first thought is that this might have to do with the way MongoEngine caches connections, but I'm not really sure.

Any guidance here?

**Comment by rozza** [comment]
Hi benweatherman, 

Aren't you creating a new connection each time in your code?

Are Celery tasks are run as separate processes? and therefore would create their own connection and cache their own connection in their own process and not share between processes?

Also in the code above are you actually closing the connection?  I cant see db being set.

This ticket is from a while ago, but any information you can add would be good :)

**Comment by benweatherman** [comment]
Yeah, basically I was leaking connections because mongoengine is using the thread or process (I forget which) to cache the connection. Not really sure there's anything that can be done except to properly close the connection explicitly (which I wasn't doing in this code...stupid me). But this might be something to point out in some documentation or allow a way to turn off connection pooling.

**Comment by rozza** [comment]
cool thanks for getting back to me,  I updated the connection process in dev https://github.com/hmarr/mongoengine/commit/1781c4638b0bc7b510c6c3cea27305fcb933941e which may help.  But I think as they  We're using celery as well, so I'll review.

**Comment by rozza** [comment]
Seems to be a pymongo issue: http://api.mongodb.org/python/1.5.1/faq.html#how-does-connection-pooling-work-in-pymongo

Closing for now, will hopefully revisit this as pymongo updates.

**Comment by benweatherman** [comment]
Great, thanks for the followup @rozza.
