### ISSUE TITLE
"_types" should be included in applicable indexes

### ISSUE THREAD

**Issue by mattdennewitz** [hmarr/mongoengine#13]
As `_types` is transparently inserted into a query spec before querying MongoDB, it should also be transparently inserted into each of a model's indexes. An index without `_types` may be overlooked by the MongoDB planner.

A [simple check](http://github.com/hmarr/mongoengine/blob/master/mongoengine/base.py#L247) for allowed inheritance [here](http://github.com/hmarr/mongoengine/blob/master/mongoengine/queryset.py#L53) would probably be enough, right?

**Comment by hmarr** [comment]
I've been meaning to add an index for `_types` for a while but I completely forgot about it - so thanks a lot for pointing that out! I've updated the repository to reflect this change.

`Document.objects` may be used without calling it, so to make index creation as lazy as possible I've put the code for creating both the `_types` and the user-defined indexes in the [`_cursor` property method](http://github.com/hmarr/mongoengine/blob/master/mongoengine/queryset.py#L64). This means that the indexes are ensured at most once if the `QuerySet` is used, but not at all if it isn't.
