### ISSUE TITLE
unique=True doesn't seems to work

### ISSUE THREAD

**Issue by k-bx** [hmarr/mongoengine#133]
Hi! I am doing
    term = StringField(max_length=200, required=True, unique=True)

but uniquness doesn't seems to be there.

Mongoengine 0.4 (latest right now from pip install))

Could someone please check if that works?

**Comment by rozza** [comment]
Hi kost-bebix - this has been fixed in dev, I think it may have been related to #129

This test case worked as expected

``` python

        class User(Document):
            name = StringField(required=True, unique=True)

        User.drop_collection()

        user = User(name='Ross')
        user.save()

        user_dupe = User(name='Ross')
        try:
            user_dupe.save()
            raise AssertionError, "We saved a dupe!"
        except OperationError:
            pass

        User.drop_collection()

```

**Comment by heyman** [comment]
Hi! I've noticed the same problem when having unique=True on fields in EmbeddedDocument classes. I guess this fix is likely to have solved the issue with unique constraints on fields in embedded documents as well?

**Comment by rozza** [comment]
FYI - conversation about Embedded documents and unique is over in #171
