### ISSUE TITLE
unique property doesn't work well with primary_key property?

### ISSUE THREAD

**Issue by huangzworks** [hmarr/mongoengine#138]
i got trouble when i use unique=True and primary_key=True in a data field at the same time, unique property seems doesn't work.
## code

```
from mongoengine import *
class User(Document):  
    name = StringField(primary_key = True,
                                       unique = True)
    password = StringField() 

import unittest  
class TestUser(unittest.TestCase):  
    def setUp(self):
        connect('test')

        self.name = "huangz"
        self.password = "nobodyknow"
        self.huangz = User(name = self.name,
                                           password = self.password)
        self.user.save()

    def test_unique_work_well(self):
        self.new = User(name = self.name,
                                     password = "new_password")
        self.assertRaises(OperationError, lambda: self.new.save())

if __name__ == "__main__":  
    unittest.main()
```
## test

```
F  
 ======================================================================
FAIL: test_unique_work_well (__main__.TestUser)  
----------------------------------------------------------------------
Traceback (most recent call last):  
  File "user.py", line 26, in test_unique_work_well
    self.assertRaises(OperationError, lambda: self.new.save())
AssertionError: OperationError not raised

----------------------------------------------------------------------
Ran 1 test in 0.024s

FAILED (failures=1)
```

**Comment by rozza** [comment]
Hi huangz1990,

Thanks for the ticket, I've added a test case explaining the behaviour.  The crux of the issue is: If you set a field as primary, then unexpected behaviour can occur.  You won't create a duplicate but you will update an existing document.

**Comment by huangzworks** [comment]
Thank you, rozza.

But i still confusing why not just raise a exception in this case?

update operating is not i expected，it may make me overwrite my original data，otherwise i must ensure the data safety by myself(check the name existed or not, etc).

**Comment by rozza** [comment]
Sure it is a little (very) odd to me! but there are no exceptions raised by pymongo or mongodb for us to catch.

You could work round it by having to use get_or_create, which is not ideal.  As primary keys must be unique in Mongo - I wouldn't advise making the username the primary key in the above example.  It can still be unique and have an index if required (you can declare it in the meta).
