### ISSUE TITLE
How can I update/delete a EmbeddedDocument item

### ISSUE THREAD

**Issue by huacnlee** [hmarr/mongoengine#139]
Some times I design model as like this:

```
class Reply(EmbeddedDocument):
    body = StringField(required=True)
    author = StringField()

class Topic(Document):
    title = StringField(required=True)
    author = StringField()
    body = StringField(required=True)
    replies = ListField(EmbeddedDocumentField(Reply))
```

How can I update/delete a Reply item? Because I can't find ObjectId or another primary key in Reply

**Comment by rozza** [comment]
Reply items are embedded - so you have to fetch the Topic and update the specific Reply.

I've added a test case showing how easy it is to update an embedded object
