### ISSUE TITLE
Add 'fail if not current' behaviour to Document.save

### ISSUE THREAD

**Issue by hmarr** [hmarr/mongoengine#14]
Dirty fields on document objects should be tracked. The `QuerySet.update()` method may be used to update the dirty fields, using the old values of the dirty fields as the query. This will mean that the update fails if the fields have been changed in the database since the object was retrieved.

**Comment by amcgregor** [comment]
This is an issue I may attempt to tackle in a fork of mongoengine; I need dirty field tracking anyway to identify fields to re-index for my full-text search engine.  Right now I'm overriding the save method in my Asset document class and doing some ugly, ugly things.  ;)

**Comment by hmarr** [comment]
Awesome - this'd be a great feature to have, just not had time to implement it. Ping me if you need a hand with anything.

**Comment by rozza** [comment]
Dirty fields are now tracked in dev
