### ISSUE TITLE
MongoDB 1.8. Map Reduce 

### ISSUE THREAD

**Issue by Ankhbayar** [hmarr/mongoengine#141]
For new Mongodb 1.8. 

PyMongo has changed. 
https://github.com/mongodb/mongo-python-driver/commit/6571f8b0e11fb59fd361eff70bf1604bc730cc3b

Function NEW required <b>out</b> parameter.
<code>Caught TypeError while rendering: map_reduce() takes at least 4 non-keyword arguments (3 given)</code>

<dist-package>/mongoengine-0.4-py2.6.egg/mongoengine/queryset.py in map_reduce, line 793

MongoEngine is latest dev branch. 
Thanks.

**Comment by samuelclay** [comment]
I fixed this on my mongoengine branch, since I'm using MongoDB 1.8: https://github.com/samuelclay/mongoengine/tree/dev. Note that I also added item_frequencies_mr, which does the same thing as item_frequencies, but using a map_reduce instead of an eval.

**Comment by Ankhbayar** [comment]
Thanks. It is merged.

**Comment by nskeip** [comment]
The same problem on pymongo  1.11((

**Comment by Ankhbayar** [comment]
Oops. That is my fault. Let Reopen. ;)
I't is working on my fork. 
But there is still error on main dev branch.

**Comment by nskeip** [comment]
Terribly sorry - posted to you by a mistake.

**Comment by rozza** [comment]
Confused - this works for me on the dev branch..  was added in: f0277736e2144130b209e0a11667e50c098ec1bc

Please reopen if that is not so!
