### ISSUE TITLE
Duplicate key error when subclassing

### ISSUE THREAD

**Issue by tfausak** [hmarr/mongoengine#143]
Defining a unique field in a subclass causes unique key errors when inserting or querying if there is more than one document without that field. Specifically, this error is thrown: `pymongo.errors.OperationFailure: E11000 duplicate key errorindex: tmp-unique.a.$foo_1  dup key: { : null }`

https://gist.github.com/885218
https://gist.github.com/885292

**Comment by rozza** [comment]
This is no longer the case in the dev branch - added your test case to catch any regressions.

Many thanks!
