### ISSUE TITLE
potentially incorrect behavior at __iter__

### ISSUE THREAD

**Issue by orenmazor** [hmarr/mongoengine#152]
Hey, I could be completely wrong here, but I'm seeing a weird behavior that may be an iter problem (not that I am an expert at handling that).

my procedure in django (1.3):

in the view:

`items = Item.objects[:20]`

which gives me 20 items, but when I pass items into my template and do:

`for item in items`

I'm iterating over all of the items in that collection and not the limited list I expect.

I've been getting around this by:

`items = list(Item.objects[:20])`

which seems wrong.

**Comment by Uznick** [comment]
Same problem here.

**Comment by rozza** [comment]
I believe this is related to #166 which has been fixed in dev and backported into master.
