### ISSUE TITLE
queryset slice doesn't work

### ISSUE THREAD

**Issue by j0hnsmith** [hmarr/mongoengine#155]
I think this is related to issue #150.

```
MyModel.objects.count()
>>> 100000
MyModel.objects.all()[80000:80001]
...
IndexError: stop index must be greater than startindex for slice slice(80000, 21, None)
```

I'm using mongoengine 0.4

**Comment by ozexpert** [comment]
i'm also having similar issue.

**Comment by rozza** [comment]
Hmm - seems to have lost my comment!

Thanks J0hnsmith - this has been fixed in dev.
Test case added here: https://github.com/hmarr/mongoengine/commit/1a049ee49d3e5fc758f9c0d5268282599f9268dc
