### ISSUE TITLE
ValidationError and model validation

### ISSUE THREAD

**Issue by stopdesign** [hmarr/mongoengine#157]
Now mongoengine.ValidationError inherited from Exception.
In this case, I can not catch the model validation error when doing validation form.
So mongoengine.ValidationError must inherit from the django.core.exceptions.ValidationError, not from the Exception.

**Comment by hmarr** [comment]
We can't inherit from Django's ValidationError as MongoEngine is framework-agnostic - this change would make Django a dependency. For forms I'd suggest looking at https://github.com/stephrdev/django-mongoforms

**Comment by rozza** [comment]
To confirm I don't use mongoengine with django :)

Closing issue as its a won't fix.
