### ISSUE TITLE
Add Spherical models tests

### ISSUE THREAD

**Issue by rozza** [hmarr/mongoengine#163]
See: https://github.com/hmarr/mongoengine/pull/162

Add tests for the spherical models as well - use glyphobet's gist

**Comment by glyphobet** [comment]
I can do this if you want. I would want to add _within_spherical_distance and _near_sphere to mongoengine's supported geospatial operators at the same time.

**Comment by rozza** [comment]
That would be awesome!

**Comment by rozza** [comment]
Fixed in https://github.com/hmarr/mongoengine/commit/6cf0cf9e7d8076773ebfebb60d4e56faa9cd49f8 and https://github.com/hmarr/mongoengine/commit/6cf0cf9e7d8076773ebfebb60d4e56faa9cd49f8
