### ISSUE TITLE
Add Django-like Meta options support

### ISSUE THREAD

**Issue by sunrize531** [hmarr/mongoengine#165]
The goal is obvious: to give your model metadata.

**Comment by rozza** [comment]
Hi, please explain what you want - models already have metadata - please can you clarify.

**Comment by sunrize531** [comment]
I want an ability to modify document's metadata just like in Django models:

```
class DocumentWithModifiedMeta(Document):
    field1 = StringField()
    field2 = StringField()

    class Meta:
        max_size = 'option1_value'
        id_field = 'pk'
```

I want the model's and model instance's attribute _meta return an instance of some class, that i could extend.
I want the fields of this class documented.

**Comment by Terr** [comment]
I think this would be a good feature. MongoEngine's models are perfectly suited for inheritance, but with the current setup you have to repeat the Meta dictionary for each subclass

**Comment by hmarr** [comment]
The same should apply in MongoEngine - options from the `meta` dict are included in document subclasses:

```
>>> from mongoengine import StringField, Document
>>> class Foo(Document):
...     username = StringField()
...     meta = {'id_field': 'username'}
...
>>> Foo._meta['id_field']
'username'
>>> class Bar(Foo):
...     pass
...
>>> Bar._meta['id_field']
'username'
```

Is it the dictionary syntax that you're unhappy with?

**Comment by Terr** [comment]
Ah, sorry, what I meant with inheritance was the ability to override some values. To use your example,  if you want to change one value the meta dictionary of Bar, you would normally have to copy/paste the entire dict to the subclass.

I'm guessing it's possible to work around this in most cases with a `self.meta.update()` in `__init__`?, but the way Django does it with an internal class looks cleaner.

**Comment by hmarr** [comment]
The _meta dict is created by settings up some defaults, merging in the base class meta dict (via dict.update()) then merging in the meta dict on the class itself (if it exists). This should give the behaviour you're describing:

```
from mongoengine import Document, StringField

class Foo(Document):
    username = StringField()
    meta = {
        'id_field': 'username',
        'ordering': ['username'],
    }

class Bar(Foo):
    meta = {
        'ordering': ['-username']
    }

# Foo's id_field is set to username
print Foo._meta['id_field'] # => username
# Foo's ordering set to ['username']
print Foo._meta['ordering'] # => ['username']
# Bar inherits id_field value from Foo (username)
print Bar._meta['id_field'] # => username
# Bar's ordering overrides Foo's value with ['-username'] (note the -)
print Bar._meta['ordering'] # => ['-username']
```

Have you found a situation where this doesn't happen?

**Comment by Terr** [comment]
I did have one case, but it has been a while ago and I don't know anymore what it was. I'll try to see if I can find it in the commit logs of a project of mine.

But the behaviour you're describing is exactly what (at least) I had in mind. Thank you for your replies and sorry for having wasted your time (unless I can find that case I had ;))

**Comment by hmarr** [comment]
No problem, glad it's working ok.
