### ISSUE TITLE
Add $slice operator to only return portions of an array

### ISSUE THREAD

**Issue by rozza** [hmarr/mongoengine#167]
In Pymongo you can:

Use the new $slice operator to only return portions of an array:

``` python

>>> db.test.find_one(fields={"z": {"$slice": 2}})
{u'y': 2, u'x': 1, u'_id': ObjectId('...'), u'z': [1, 2]}
>>> db.test.find_one(fields={"z": {"$slice": -2}})
{u'y': 2, u'x': 1, u'_id': ObjectId('...'), u'z': [3, 4]}
>>> db.test.find_one(fields={"z": {"$slice": [1, 2]}})
{u'y': 2, u'x': 1, u'_id': ObjectId('...'), u'z': [2, 3]}

```

**Comment by hmarr** [comment]
Interesting - got any thoughts on the API for this?

**Comment by rozza** [comment]
Hi, its a fields operator so I can add a method similar to .only() and .exclude() as in the backend they are effectively do the same thing.

I'm -1 on slice() as people with think it slices a queryset not an embedded field.

How about a simple `.fields()` method:

``` python

    def fields(self, **fields):
        for field, value in fields.items():
            fields = self._fields_to_dbfields([field])
            self._loaded_fields += QueryFieldList(fields, direction=value)
        return self
```

Works fine eg:

``` python

    def test_slice_operator(self):
        """Ensure that field slicing an array works.
        """

        class Numbers(Document):
            n = ListField(IntField())

        Numbers.drop_collection()

        numbers = Numbers(n=[0,1,2,3,4,5,-5,-4,-3,-2,-1])
        numbers.save()

        # first three
        numbers = Numbers.objects.fields(n={"$slice": 3}).get()
        self.assertEquals(numbers.n, [0, 1, 2])

        # last three
        numbers = Numbers.objects.fields(n={"$slice": -3}).get()
        self.assertEquals(numbers.n, [-3, -2, -1])

        # skip 2, limit 3
        numbers = Numbers.objects.fields(n={"$slice": [2, 3]}).get()
        self.assertEquals(numbers.n, [2, 3, 4])

        # skip to fifth from last, limit 4
        numbers = Numbers.objects.fields(n={"$slice": [-5, 4]}).get()
        self.assertEquals(numbers.n, [-5, -4, -3, -2])

        # skip to fifth from last, limit 10
        numbers = Numbers.objects.fields(n={"$slice": [-5, 10]}).get()
        self.assertEquals(numbers.n, [-5, -4, -3, -2, -1])
```

it mimics pymongo syntax and means I wouldn't have to add a .slice_field() method..

What you think?

**Comment by rozza** [comment]
Checkout: https://github.com/hmarr/mongoengine/tree/feature%2Fslicing_fields

Let me know what you think!

**Comment by hmarr** [comment]
Looks good - seems like a solid implementation. Only thought is that the api is a bit inconsistent with the rest of the codebase as it uses dicts rather than the Django-style double underscore syntax. Something like this might work:

``` python
Numbers.objects.fields(slice_n=[-5, 10]).get()
```

Not completely against the dict syntax, but would be interested to hear your opinion.

**Comment by rozza** [comment]
Hmm yeah good point :) will convert to `slice__n` tomorrow :)

**Comment by rozza** [comment]
@hmarr - will merge post review :)

**Comment by hmarr** [comment]
Looks great - cheers for that, feel free to merge!

At some point it may be worth separating out the kwarg parsing code as it's used in a few places in the codebase, but that's more of a rainy day refactoring I guess.

**Comment by rozza** [comment]
Done and merged.  Added #173 for the refactoring
