### ISSUE TITLE
[proposal] allow_inheritance: False by default

### ISSUE THREAD

**Issue by k-bx** [hmarr/mongoengine#169]
Hi everyone!

I would like to propose to disable allow_inheritance feature by default (and fix documentation for that)
1. It's not so commonly used feature (i guess)
2. it inserts a lot of junk (and you notice it only after you insert documents and query for them "by hands" to check something).

Thank you.

**Comment by rozza** [comment]
+1 also - Abstract base class can be used for backwards compatibility.

``` python
class BaseDocument(Document):
        meta = {
            'abstract': True,
            'allow_inheritance': True
        }

...

# from mongoengine import Document
from models import BaseDocument as Document
```

**Comment by k-bx** [comment]
Ok, that's nice to know (I'll use that). How about making BaseDocument and deprecating Document in few releases?

**Comment by rozza** [comment]
Ok after feedback from users - decided that allow_inheritance is a good thing by default and turning off is easier than turning on in the future - so this is a no fix.
