### ISSUE TITLE
Enforced presence of "_types" in index prevents indexing a ListField

### ISSUE THREAD

**Issue by mattdennewitz** [hmarr/mongoengine#17]
Compound indexes cannot contain two lists, as it causes unreasonable index growth (n^2). Transparently including `_types` in an index prevents including a `ListField` -- MongoDB "cannot index parallel arrays".

```
Buildindex baseballapp.game idxNo:3 { name: "_types_1_player_ids_1", ns: "baseballapp.game", key: { _types: 1, player_ids: 1 }, unique: false }
User Exception cannot index parallel arrays
```

**Edit:** this can possibly be solved by not adding `_types` to indexes that contain `ListFields`, and then using `Cursor.hint()` to tell the query optimizer to use the index every though `_types` is in the query.

**Comment by hmarr** [comment]
I've just committed a change that removes `_types` from `ListField` indexes - was going to have a go with using `hint()` but [benchmarks](http://gist.github.com/278859) seem to indicate that the query planner picks up on the index even though `_types` isn't present. Still, I think it would be nice to use `hint()` for the cases where the index isn't noticed.
