### ISSUE TITLE
Document classes aren't automatically added to _document_registry when using GenericReferenceField

### ISSUE THREAD

**Issue by atroche** [hmarr/mongoengine#170]
I have a document which has a GenericReferenceField that I use to reference a document defined in another file. Neither the document being referenced nor the file containing it are imported anywhere in the file containing the original document with the GenericReferenceField.

When mongoengine goes to dereference the DBRef in the GenericReferenceField, it fails because the referent has not been added to the global _document_registry.

I shouldn't have to explicitly import any models I might reference at some point, right?

**Comment by rozza** [comment]
Yeah I have a feeling that you do have to import them to the registry.

Django would handle that as it auto discovers all models.py from `INSTALLED_APPS` so there you probably don't have to worry about it.

I'll add something to the docs saying you may have to manually import all models / write an auto discovery mechanism to ensure this works.
