### ISSUE TITLE
Document.save() should only update dirty fields

### ISSUE THREAD

**Issue by hmarr** [hmarr/mongoengine#18]
Using `pymongo.collection.Collection.save()` replaces the document in the DB with the one being saved if the ids match. This could be an issue if two clients retrieve an object, then both try to save it (see [issue 14](http://github.com/hmarr/mongoengine/issues/#issue/14) for more info). To reduce the effect of this, `Document.save()` could call `Collection.update()` with only the dirty parameters, using the object's id as the update query. 

An example of this being useful is a blogging application, where each page object has a `page_views` field which is always updated using `$inc`. Without this adjustment, when saving changes to a post, any hits to the page between when the server retrieved a post, and when it called `save()` would be lost as the retrieved value would be restored.

**Comment by yashh** [comment]
How do we know that this is a Document update. When I get a document with 

```
x = Model.objects.get(something='something')
x.something='somethingelse'
x.save()
```

I think there should be a seperate method x.update({}) which accepts a dict of updated parameters. If its possible via save can you explain me, so that I can fork and work on it.

**Comment by amcgregor** [comment]
I would imagine this working entirely behind-the-scenes, with an enabler argument (say, `minimal` or `delta`) to `.save()` to enable the behaviour of only saving (transmitting over-the-wire) dirty fields.

Having an `.update()` method is separate, but also good, though it does raise a minor issue with updating nested attributes (no really elegant way to do that in a flat dict).

**Comment by zhangcheng** [comment]
I took a shoot at this with [f4d4d2](https://github.com/zhangcheng/mongoengine/commit/f4d4d29aef65a3d0acfa3e5b25fa076d524e48cb)

**Comment by zhangcheng** [comment]
@rozza please take a look, I made the change on dev branch per d6442db2.

**Comment by rozza** [comment]
wow - looks great @ zhangcheng

**Comment by rozza** [comment]
@zhangcheng thats in and fixes #146

Its not quite a delta / check of explicit changes - so race conditions still exist.  In those scenarios using .only() or .exclude() on fields not explicitly set would help.

**Comment by rozza** [comment]
This is nearly done - should be fixed tomorrow

**Comment by rozza** [comment]
This is now in `dev`

**Comment by BobDickinson** [comment]
I think I am having an issue with this fix.  I have a document that contains a recursively embedded document set (a tree of folders and folder content items).

The structure is something like:

class FolderItem(db.EmbeddedDocument):
    name = db.StringField() 

class Folder(FolderItem):
    contents = db.ListField(db.EmbeddedDocumentField(FolderItem), default=[])

class FolderTree(db.Document):
    root = db.EmbeddedDocumentField(Folder, default=lambda: Folder())

This is a folder tree where a Folder item can contain any combination of Folder or FolderItems.

If I change the Folder referenced from the FolderTree document, everything works fine.  If I change any descendant Folder or FolderItem below the root, MongoEngine does not track the change and does not save it.  I have verified this by watching _get_changed_fields() and _delta() in the save override on the FolderTree document (it shows the changes you would expect when modifying root, but never shows the changes made to any embedded documents that root contains).

This is compounded by the fact that I don't see any way to say "hey, stop trying to outsmart me and just save the whole document every time" (not what I want, but better than what I have).  So what I do now is a root=root in the save override (I actually have five of these fields, so I do it for all five).
