### ISSUE TITLE
Add DjangoReferenceField

### ISSUE THREAD

**Issue by colinhowe** [hmarr/mongoengine#182]
Hello,

We have some of our models in Mongo and some in MySQL (handled by Django). We often want our mongo documents to reference back to models in Django. To make it easier we made DjangoReferenceField. Usage is:

``` python
class Post(Document):
    owner = DjangoReferenceField('myapp.UserProfile')
```

This works in the same way as ReferenceField (can set using an ID or an instance, etc).

I propose the code below is added into the Django helpers that already exist :)

``` python
from mongoengine.base import BaseField, ValidationError
from django.db import models 
from django.db.models.loading import get_model

class DjangoReferenceField(BaseField):
    """A reference to a model within Django that will be automatically 
    dereferenced on access (lazily).
    """

    def __init__(self, document_type, **kwargs):
        if not isinstance(document_type, basestring):
            if not issubclass(document_type, (models.Model, basestring)):
                raise ValidationError(
                    'Argument to DjangoReferenceField constructor must be a '
                    'model class or a string')
        self.document_type_obj = document_type
        super(DjangoReferenceField, self).__init__(**kwargs)

    @property
    def document_type(self):
        if isinstance(self.document_type_obj, basestring):
            app_label, model_name = self.document_type_obj.split('.')
            self.document_type_obj = get_model(app_label, model_name)
        return self.document_type_obj

    def __get__(self, instance, owner):
        """Descriptor to allow lazy dereferencing.
        """
        if instance is None:
            # Document class being used rather than a document object
            return self

        # Get value from document instance if available
        value = instance._data.get(self.name)
        # Dereference DBRefs
        if isinstance(value, (int, long)):
            value = self.document_type.objects.get(id=value)
            if value is not None:
                instance._data[self.name] = value

        return super(DjangoReferenceField, self).__get__(instance, owner)

    def to_mongo(self, document):
        if isinstance(document, models.Model):
            # We need the id from the saved object to create the DBRef
            id_ = document.id
            if id_ is None:
                raise ValidationError('You can only reference models once '
                                      'they have been saved to the database')
        else:
            id_ = document

        return id_

    def prepare_query_value(self, op, value):
        return self.to_mongo(value)

    def validate(self, value):
        assert isinstance(value, (self.document_type, int, long))

    def lookup_member(self, member_name):
        return self.document_type._fields.get(member_name)
```

**Comment by colinhowe** [comment]
Bah, I based this so much on ReferenceField that I failed to change the comment in to_mongo :)

Also, it's worth noting that this only supports Django models that use the auto-generated primary key. 

Also #2, as this is lazy loading doing the dereference lots of times won't be efficient on large sets but it isn't hard to implement that.

**Comment by iapain** [comment]
It does not appeal to me the need why we should have a `DjangoReferenceField` in core mongoengine itself. If it's very much required then there are very neat workrounds are there.

**Comment by colinhowe** [comment]
It's not _needed_. But, nor is anything in the django package. It's something that makes working with Django and MongoDB a lot easier.

I'd be happy to see the existing package ripped out and put in a separate project.

**Comment by rozza** [comment]
+1 for moving djangomongoengine out into its own project with tests but thats not going to happen in the short term..

I'm happy to add to the django code base in a fields.py

**Comment by rozza** [comment]
I'm happy for this to be added into the django based code until such a time as that gets abstracted out.

@colinhowe if you do a pull request, perhaps with some tests as I've changed how we lazily dereference I'll add it.  Alternatively, you could add to the docs in the django section.
