### ISSUE TITLE
DateTime object not properly saved / loaded

### ISSUE THREAD

**Issue by pelletier** [hmarr/mongoengine#187]
```
from datetime import datetime
from mongoengine import Document, DateTimeField, connect


connect("mongoenginefails")


class Example(Document):
    date = DateTimeField(required=True)


d = datetime(1954,10,03,21,25,04,140000)

c = Example(date=d)

for obj in Example.objects.all():
    obj.delete()

print c.date
c.save()
print Example.objects.first().date
```

The output is:

```
1954-10-03 21:25:04.140000
1954-10-03 21:25:05.15917216
```

It's obviously not what I expect. First the two dates are not equal, and the 
second (the retrieved one) has 8 digits to its `microsecond` attribute ([which
is wrong](http://docs.python.org/library/datetime.html#datetime.datetime.microsecond)).

For the record, here are my software versions:
- MongoDB 1.8.1 OS X x64 (also fails on Ubuntu 10.04 x64)
- Python 2.7.1 (also fails on 2.6).
- Mongoengine c059ad47f24394c3bb3f4b4f24a6f9e91280c4ab (also fails on 69989365c7cb4c26d77882fdc5e9962ccf2b9755)
- Pymongo 1.9 (from pypi)

**Comment by rozza** [comment]
Hi,

Seems - microseconds are rounded in pymongo / mongo - http://api.mongodb.org/python/1.7/api/pymongo/son.html#id1

Doing it directly via pymongo yields the same results:

``` python
    def test_datetime(self):
        """Ensure that datetime fields are saved and stored correctly
        """
        class LogEntry(Document):
            date = DateTimeField()

        LogEntry.drop_collection()
        d = datetime.datetime(1954, 10, 03, 21, 25, 04, 140000)
        log = LogEntry()
        log.date = d
        log.save()

        log = LogEntry.objects.first()
        self.assertEquals(log.date, d)

        db = _get_db()
        collection = db[LogEntry._meta['collection']]
        collection.insert({'date': d, '_types': ['LogEntry'], '_cls': 'LogEntry'})

        log_1 = LogEntry.objects[1]
        self.assertEquals(log_1.date, d)
```

**Comment by rozza** [comment]
Unfortunately, this is a won't fix -  as its out of our hands.

cfcd77b193da1eb03ef5632f88cd2189f58b2974 - updated the docs and added test cases displaying datetime handling by pymongo/mongodb

**Comment by pelletier** [comment]
For the record, here is a custom Mongoengine field (+tests) I wrote to get rid of this problem:

http://www.friendpaste.com/6xoqAtoUYdCzq7hNtD6xoo

**Comment by rozza** [comment]
awesome - do you mind if tweak and add to mongoengine?

**Comment by rozza** [comment]
@pelletier have added it to dev - thanks for the ticket and the code.
