### ISSUE TITLE
add get_FIELD_display Django Like to Document

### ISSUE THREAD

**Issue by wpjunior** [hmarr/mongoengine#188]
example:

class Post(Document):
    a = ChoiceField(choices=(('gdm', 'GNOME DISPLAY MANAGER'), ('kde', 'KDE DISPLAY MANAGER')))

p = Post()
p.a = 'gdm'

p.get_a_display() -> "GNOME DISPLAY MANAGER"

**Comment by rozza** [comment]
Its in the **dev** branch
