### ISSUE TITLE
Ordered QuerySet still show natural order in Django's template

### ISSUE THREAD

**Issue by zhangcheng** [hmarr/mongoengine#190]
I wrote [a test case](https://github.com/zhangcheng/mongoengine/commit/1eeb27b344b688579a5fa3d9d19c60256b4f1868) to show the problem.

> # 
> 
> FAIL: test_order_by_in_django_template (tests.queryset.QuerySetTest)
> ## Ensure that QuerySets are properly ordered in Django template.
> 
> Traceback (most recent call last):
>   File "/mnt/DataHD/Users/czhang/repo/git-hub/mongoengine/tests/queryset.py", line 785, in test_order_by_in_django_template
>     self.assertEqual(t.render(Context(d)), u'A20B40C30D10')
> AssertionError: u'A20B40D10C30' != u'A20B40C30D10'

**Comment by rozza** [comment]
Hi zhangcheng,

Thanks for the testcase - there was a slight bug in the testcase, so I've updated it and added to the dev branch where this issues is fixed.
