### ISSUE TITLE
add DateField

### ISSUE THREAD

**Issue by wpjunior** [hmarr/mongoengine#191]
class Person(Document):
    nome = StringField()
    birth = DateField()

p = Person()
p.nome = "Juca"
p.birth = datetime.date.today()
p.save()

**Comment by rozza** [comment]
Hi all dates are stored as datetimes in mongodb (http://api.mongodb.org/python/1.7/faq.html#how-can-i-save-a-datetime-date-instance).

So I've fixed the DateTimeField to handle dates.
