### ISSUE TITLE
verbose_name and help_text in Fields

### ISSUE THREAD

**Issue by wpjunior** [hmarr/mongoengine#192]
Class Person(Document):
name = StringField(verbose_name= "Name of Person", help_text="blah blah blah for add name")

for the futher use of mongoforms

**Comment by wpjunior** [comment]
Pull request: https://github.com/wpjunior/mongoengine/commit/b93801e4857e09101b81e8cc8dd2ec8d795755cb

**Comment by rozza** [comment]
Please can you see if there is more support  for this on the email user list.
