### ISSUE TITLE
Document.objects.item_frequencies bug

### ISSUE THREAD

**Issue by wpjunior** [hmarr/mongoengine#194]
Moradia.objects.item_frequencies('endr')

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "mongoengine/queryset.py", line 1403, in item_frequencies
    return self._item_frequencies_exec_js(field, normalize=normalize)
  File "mongoengine/queryset.py", line 1476, in _item_frequencies_exec_js
    return self.exec_js(freq_func, field, normalize=normalize)
  File "mongoengine/queryset.py", line 1349, in exec_js
    return db.eval(code, *fields)
  File "/usr/lib/python2.7/site-packages/pymongo/database.py", line 570, in eval
    result = self.command("$eval", code, args=args)
  File "/usr/lib/python2.7/site-packages/pymongo/database.py", line 293, in command
    msg, allowable_errors)
  File "/usr/lib/python2.7/site-packages/pymongo/helpers.py", line 126, in _check_command_response
    raise OperationFailure(msg % response["errmsg"])
pymongo.errors.OperationFailure: command SON([('$eval', Code('\n            function(field) {\n                if (options.normalize) {\n                    var total = 0.0;\n                    db[collection].find(query).forEach(function(doc) {\n                        if (doc[field].constructor == Array) {\n                            total += doc[field].length;\n                        } else {\n                            total++;\n                        }\n                    });\n                }\n\n                var frequencies = {};\n                var inc = 1.0;\n                if (options.normalize) {\n                    inc /= total;\n                }\n                db[collection].find(query).forEach(function(doc) {\n                    if (doc[field].constructor == Array) {\n                        doc[field].forEach(function(item) {\n                            frequencies[item] = inc + (isNaN(frequencies[item]) ? 0: frequencies[item]);\n                        });\n                    } else {\n                        var item = doc[field];\n                        frequencies[item] = inc + (isNaN(frequencies[item]) ? 0: frequencies[item]);\n                    }\n                });\n                return frequencies;\n            }\n        ', {'query': {'_types': 'Moradia'}, 'options': {'normalize': False}, 'collection': 'moradia'})), ('args', ('endr',))]) failed: invoke failed: JS Error: TypeError: doc[field] has no properties nofile_b:18

**Comment by rozza** [comment]
Hi @wpjunior - I'm going to need some more information to be able to do anything to help fix..

What version of mongoengine / mongodb?
Can you provide a testcase?

**Comment by wpjunior** [comment]
mongodb: 1.8.1
mongoengine-dev
python2-pymongo 1.10.1-1

**Comment by rozza** [comment]
cool - will need a testcase then.  The current test cases show it working..

**Comment by wpjunior** [comment]
``` python
from mongoengine import connect
from mongoengine import *
connect('teste')

class Phone(EmbeddedDocument):
    res = StringField(verbose_name="Residencial", max_length=16)

class Person(Document):
    phone = EmbeddedDocumentField(Phone)

if __name__ == '__main__':
    doc = Person()
    doc.phone = Phone(res='62-3331-1656')
    doc.save()

    doc = Person()
    doc.phone = Phone(res='62-3331-1656')
    doc.save()

    doc = Person()
    doc.phone = Phone(res='62-3332-1656')
    doc.save()

    Person.objects.item_frequencies('phone.res')
```

**Comment by rozza** [comment]
thanks will look into

**Comment by wpjunior** [comment]
in ReferenceField

``` python
from mongoengine import connect
from mongoengine import *
connect('teste')

class Phone(Document):
    res = StringField(verbose_name="Residencial", max_length=16)

class Person(Document):
    phone = ReferenceField(Phone)

if __name__ == '__main__':
    Person.drop_collection()
    Phone.drop_collection()

    ph = Phone(res='62-3331-1656')
    ph.save()

    doc = Person()
    doc.phone = ph
    doc.save()

    print Person.objects.item_frequencies('phone.res')
```

**Comment by rozza** [comment]
You cannot map across references - you'd have to write your own map reduce method.
