### ISSUE TITLE
Update docs

### ISSUE THREAD

**Issue by rozza** [hmarr/mongoengine#207]
For the pending 0.5 release..

**Comment by dcrosta** [comment]
One of my patches addressed this by adding a .update() method on Document. Want me to rejigger that into a pull request for this issue?

**Comment by rozza** [comment]
No this ticket is for updating the documentation for the 0.5 release!

**Comment by dcrosta** [comment]
Haha, ok. Guess my pull doesn't fix that, then :)

**Comment by rozza** [comment]
Lots of doc updates today!
