### ISSUE TITLE
Infinite recursion when getting _geo_indices [dev]

### ISSUE THREAD

**Issue by joshink** [hmarr/mongoengine#213]
It seems two documents can no longer contain a reference to each other:

``` python

class User(Document):
    channel = ReferenceField('Channel')

class Channel(Document):
    user = ReferenceField('User')

```

This will cause infinite recursion when `QuerySet._collection` is accessed because of the _geo_indicies lookup. Looks like `Document._geo_indicies()` will try to get ReferenceField documents and then recursively get that referenced document's reference fields and so on. This would obviously work fine until one document referenced another with a reverse relationship. 

I know I should probably submit a pull request, but your solution would be much more elegant then my own. I would probably just do some memorization of geo indexed fields. Cheers!

**Comment by rozza** [comment]
Thanks for the bug report @joshink

**Comment by joshink** [comment]
No problem. Looks good. Sorry I didn't do it myself, will next time ;)
