### ISSUE TITLE
infinite recursion of multiple reference fields

### ISSUE THREAD

**Issue by wpjunior** [hmarr/mongoengine#214]
my test case :-)
from mongoengine import connect
from mongoengine import *
connect('teste')

class Person(Document):
    name = StringField()
    parent = ReferenceField('self')
    friend = ReferenceField('self')                     

if **name** == '**main**':
    Person.drop_collection()

```
p1 = Person(name="Wilson Jr")
p1.parent = None
p1.save()

p2 = Person(name="Wilson Jr2")
p2.parent = p1
p2.save()

p1.friend = p2
p1.save()

p0 = Person.objects.first()
p0.name = 'joia'
p0.save()
```

**Comment by rozza** [comment]
Thanks - all fixed!
