### ISSUE TITLE
Should serialization dereference DBRefs?

### ISSUE THREAD

**Issue by mattdennewitz** [hmarr/mongoengine#22]
python's `json` module won't call `__get__` when serializing a `Document`, so raw `DBRef` objects are returned. should `DBRef`s somehow be dereferenced when serializing a `Document`?

**Comment by hmarr** [comment]
I reckon that just serialising the `_id` would be sufficient. Django also seems to take that route.

**Comment by mattdennewitz** [comment]
thats fair.
