### ISSUE TITLE
Don't ensure_index on each query

### ISSUE THREAD

**Issue by dcrosta** [hmarr/mongoengine#223]
Even though pymongo is "smart" about duplicate calls to ensure_index, we should not be constantly re-ensuring the indices. Instead, do this only the first time a collection is queried, or when the class is first loaded. Mostly we need to improve the bookkeeping in QuerySet to effect this change, which should be simple. I'll take a crack at this this week.

**Comment by rozza** [comment]
I'm not sold on this, pymongo has a solid implementation as it also keeps a cache, whats more you can call and remove items from its cache.

**Comment by dcrosta** [comment]
pymongo only caches this data for 300 seconds (5 minutes) by default, after which time calls to ensure_index() will hit the database (they won't create the index, as it already exists)... this is extra work that needn't be done, especially since the model and indexes defined can't (or at least shouldn't) change once the model class is loaded in the interpreter.

I'd actually prefer to have index creation done during _class_ initialization, but that's a more significant change (and `connect()` may not have been called at that point, and other confounding issues as well), so I see this as a compromise solution. The bookeeping is no more complicated than was done before, but results in greater efficiency and more predictable code.

**Comment by rozza** [comment]
fair play
