### ISSUE TITLE
Pseudo-ReferenceField

### ISSUE THREAD

**Issue by mattdennewitz** [hmarr/mongoengine#23]
Per IRC conversation with one of the 10gen-ers, it sounds like storing an `ObjectId` is more efficient than storing a `DBRef`, and a `DBRef` is little more than a glorified `findOne`. If the document that this field references is a constant, there really isn't a reason to use a `DBRef` -- it would be safe to accept a document subclass to store with the field instance, and perform a `findOne` on `__get__`.

Though, modules like the `json` module don't call `__get__` to retrieve a value. I'm not sure what we'd need to do there.

Here's a quick example:

```
class LazyReferenceField(fields.BaseField):
    """A reference to an ObjectId and model that will be 
    magically "dereferenced" on access (lazily).

    This field simulates a ``DBRef``, but only stores an ``ObjectId``.
    Data is fetched from the given ``document_type`` as necessary
    by ``__get__``.

    :param document_type: a ``Document`` subclass
    """

    def __init__(self, document_type, **kwargs):
        if not issubclass(document_type, Document):
            raise ValidationError('Argument to LazyReferenceField constructor '
                                  'must be a top level document class')
        self.document_type = document_type
        super(LazyReferenceField, self).__init__(**kwargs)

    def __get__(self, instance, owner):
        """Custom descriptor to allow lazy pseudo-dereferencing.
        """
        if instance is None:
            return self

        # Get value from document instance if available
        doc_id = instance._data.get(self.name)

        if isinstance(doc_id, pymongo.objectid.ObjectId):
            value = self.document_type.objects(id=doc_id).first()
            if value is not None:
                instance._data[self.name] = value
            return value

        return doc_id
```

**Comment by hmarr** [comment]
What did the 10gen-er say was inefficient about `DBRef`s? It looks like `DBRef`s still work when `_id`s aren't `ObjectId`s, this would also need to handle those cases.

**Comment by mattdennewitz** [comment]
i think its less to do w/ the inefficiency of a `DBRef`, and more that storing an `ObjectId` instead of a `DBRef` is better when "referencing" a collection that won't change. this implementation fakes a `DBRef` where one is not required, while still allowing the convenience of auto-dereferencing.

**Comment by rozza** [comment]
dereferencing is now done efficiently in dev branch...

**Comment by pitchfork** [comment]
holy smokes

**Comment by rozza** [comment]
Checkout the tests: https://github.com/hmarr/mongoengine/blob/dev/tests/dereference.py

**Comment by danaki** [comment]
An excerpt from the book: 50 Tips and Tricks for MongoDB Developers, Tip #17: Do not use database references

> If you are referencing a document but already know the collection, you might as well save the space and store just the _id, not the _id and the collection name. A database reference is a waste of space unless you do not know what collection the referenced document will be in.

Well, If I know that collection I'm refering to always be one and the same, I would like to use just ObjectId's to refer, DBRef() with it's 'collection' and 'database' refs are unnecessary. It would be nice to introduce a new field type RefObjectId(collection) that would act as ReferenceField(), e.g. could be dereferenced and "cascade"s would work to.

I think this is what mattdennewitz mentioned.

**Comment by rozza** [comment]
Hi as this ticket is closed it would be better to create a new ticket if you want some way to reference via just an _id..

It is a good tip though - makes the documents lighter so its not a problem to do that - just a breaking change..
