### ISSUE TITLE
Future: add serializers for querysets

### ISSUE THREAD

**Issue by wpjunior** [hmarr/mongoengine#230]
example:
# serializing

Person.objects.serialize('xml')
Person.objects.serialize('yaml')

a = open('output.xml', 'wb')
Person.objects.serialize('xml', fields=('data.name', 'endr'), out=a)
# deserialize

data = open('input.xml', 'rb').read()
objs = Person.objects.deserialize('xml', data)

for obj in objs;
    obj.save()

**Comment by wpjunior** [comment]
if you need help, I am willing to contribute to the code :-)

**Comment by rozza** [comment]
Duplicate of #210
