### ISSUE TITLE
reverse_delete_rule fails in ListField(ReferenceField)

### ISSUE THREAD

**Issue by wpjunior** [hmarr/mongoengine#254]
for this test case

``` python
import datetime
from mongoengine import *
connect('teste')

class Person(Document):
    name = StringField()

class Car(Document):
    owners = ListField(ReferenceField(Person,
                       reverse_delete_rule=NULLIFY))

Person.drop_collection()
Car.drop_collection()

p1 = Person(name="wilson")
p1.save()

p2 = Person(name="maria")
p2.save()

c = Car(owners=[p1, p2])
c.save()

p1.delete()

c = Car.objects.first()
assert c.owners == [p2]
```

**Comment by skecer** [comment]
Hi guys. is there a solution for this issue. I need this feature.  And if I want to save c after deleting p1, in the example above. I get this error:

```
...
p1.delete()
c = Car.objects.first()
c.owners 

 OUTPUT:    [DBRef(u'person', ObjectId('4e8aeba68ebfa80870000000')),<Person: Person object>]

c.save()

ValidationError: DBRef(u'person', ObjectId('4e8aeba68ebfa80870000000')) is not valid ObjectId
```

**Comment by oaylanc** [comment]
your _meta property looks like:

{'abstract': False,
 'allow_inheritance': True,
 'collection': 'person',
 'delete_rules': {},
 'id_field': 'id',
 'index_background': False,
 'index_drop_dups': False,
 'index_opts': {},
 'indexes': [],
 'max_documents': None,
 'max_size': None,
 'ordering': [],
 'queryset_class': <class 'mongoengine.queryset.QuerySet'>,
 'unique_indexes': []}

exception reason is delete_rules is empty, it must be filled if you are using ListField with ReferenceField

**Comment by maxcountryman** [comment]
+1, this is turning into a big problem for me

**Comment by bluemoon** [comment]
I have the same issue, what is the best way to solve this?

**Comment by rozza** [comment]
Sorry for the delay, I will review and get a fix in 0.6 ..

**Comment by maxcountryman** [comment]
Ross, thanks for the reply! Hoping to see this patched soon. :)

**Comment by rozza** [comment]
Done and in dev - we dont support MapFields / DictFields and will throw an InvalidDocument Error

**Comment by MeirKriheli** [comment]
IMO for ListField(ReferenceField) one more reverse_delete_rule should be added - PULL,

When it's PULL it will pull the reference from the array (instead of nullifying the field or cascading delete).

**Comment by rozza** [comment]
Please add as a feature request in a new ticket :)

**Comment by MeirKriheli** [comment]
Heh, feature request are lame ;-)

Sent a pull request implementing this, including docs and tests, see #515.
