### ISSUE TITLE
Unknown m/r field for sharding

### ISSUE THREAD

**Issue by ericmsauer** [hmarr/mongoengine#258]
Hello again, (Thought it would be better to post here)

I am trying to get mongoengine to work with a sharded database however,
I was testing the new v.4 in a different file and I got this.

edit after testing: It seems that only avg and sum (so far) are the only ones not working.
After your fix to not use db.eval()

It works with a nonsharded database, and my sharded database is set up fine... Ive triple checked it.

----------------------------Code-----------------------------------
from models import \* 
import re
import random
import os, sys
import mongoengine
from mongoengine import *
from datetime import datetime

PATH = os.path.join(sys.path[0], sys.argv[0]).split('kfe_django')[0]
DB_NAME = 'kfe'
GROUPING = 20  # how many nodes to "group" by when displaying a tree view.
HOST_PREFIX = 'kn'

db = connect(DB_NAME)

print(Host.objects.count())
avg_mem = Host.objects.average('mem_used')
print(avg_mem)

-----------------------------------Output----------------------------------------------
7826
File "shardtest.py", line 17, in <module>
    avg_mem = Host.objects.average('mem_used')
  File "build/bdist.linux-i686/egg/mongoengine/queryset.py", line 1471, in average
  File "build/bdist.linux-i686/egg/mongoengine/queryset.py", line 946, in map_reduce
  File "build/bdist.linux-i686/egg/pymongo/collection.py", line 1073, in inline_map_reduce
  File "build/bdist.linux-i686/egg/pymongo/database.py", line 340, in command
  File "build/bdist.linux-i686/egg/pymongo/helpers.py", line 126, in _check_command_response
pymongo.errors.OperationFailure: command SON([('mapreduce', u'host'), ('map', Code('\n            function() {\n                if (this.hasOwnProperty(field))\n                    emit(1, {t: this[field] || 0, c: 1});\n            }\n        ', {'field': 'mem_used'})), ('finalize', Code('\n            function(key, value) {\n                return value.t / value.c;\n            }\n        ', {})), ('reduce', Code('\n            function(key, values) {\n                var out = {t: 0, c: 0};\n                for (var i in values) {\n                    var value = values[i];\n                    out.t += value.t;\n                    out.c += value.c;\n                }\n                return out;\n            }\n        ', {})), ('keeptemp', False), ('query', {'_types': 'Host'}), ('out', {'inline': 1})]) failed: unknown m/r field for sharding: keeptemp

**Comment by dcrosta** [comment]
From http://www.mongodb.org/display/DOCS/MapReduce:

MongoDB 1.7.4+: the output options have changed. Map-reduce no longer generates temporary collections (thus, `keepTemp` has been removed). Now, you must always supply a value for `out`.

I can submit a patch this afternoon or tomorrow.

**Comment by dcrosta** [comment]
Before I do, @hmarr and @rozza, do you want to support pre-1.7.4 versions of MongoDB for map-reduce? Simplest change would be to just remove `keeptemp` from the M-R invocation.

**Comment by ericmsauer** [comment]
Alright thank you so much again!

**Comment by ericmsauer** [comment]
Just to make sure and its not computer but the new update about 2 hours ago did not fix the issue yet. I was wondering when you are going to or what i can do to help

**Comment by dcrosta** [comment]
@Plike922 right, no one has patched this bug yet. Why did you close this issue? Can you reopen it?

**Comment by ericmsauer** [comment]
There we go sorry, apparently there is a "comment & close" button right next to the "comment" button

**Comment by rozza** [comment]
Hi,

For the time being, I'm marking this as a Wont Fix  - we discussed pymongo versions on the mailinglist (https://groups.google.com/d/msg/mongoengine-users/B3hjmNDYWjo/8MOBCB-NsE4J) Currently, 0.5 is expected to support pymongo 1.11+ which also means MongoDB 1.7.4+  And there are some breaking changes upgrading from 0.4 - but these have been partially documented and will be updated before release.

Any feedback please discuss on the mailing list or supply patches :)  Personally, I'm not too keen on lots of forking of logic to check versions in such an early release as it stores up problems for testing and maintaining in the future (but thats just my opinion and I'm often wrong!).

Ross

**Comment by dcrosta** [comment]
If we're supporting mongod 1.7.4+ only, we should remove `keeptemp`.

**Comment by ericmsauer** [comment]
Hey,

Alright so I understand what you are saying sort of. You just dont know how to do muti-verison support.

But I was wondering if you can guide me to changing to support 1.7.4+... I think i have it but its not working

**Comment by rozza** [comment]
Its not a case of dont know how - its more of a case there has been no call for it from the community for 0.5 to support < 1.7.4 and therefore its cleaner not to.

So to confirm - what version of pymongo and mongodb are you running @Plike922?

**Comment by ericmsauer** [comment]
Sorry for the assumption just didnt not understand. Anyway, Im using 1.8.2 MongoDB and Pymongo I am still finding out
edit: I believe 2.0.1

**Comment by dcrosta** [comment]
@Plike922, can you open your mongo shell and do "db.serverStatus().version" ? I think your server must be older than 1.8.2 if you are seeing this error...

**Comment by rozza** [comment]
OK - no worries - sorry this is definitely a bug will fix asap.

**Comment by ericmsauer** [comment]
"version" : "1.8.2",

**Comment by ericmsauer** [comment]
See I think it is because you guys are support 1.7.4- Not the other way around @dcrosta

**Comment by dcrosta** [comment]
Sorry, I mis-read the bug report. I'll patch and resubmit.

**Comment by rozza** [comment]
@dcrosta no worries I've patched :)
@Plike922 - should be fixed now!

**Comment by ericmsauer** [comment]
Thank You Very Much!
