### ISSUE TITLE
__ilike filter

### ISSUE THREAD

**Issue by dvv** [hmarr/mongoengine#26]
---
## Class.objects(name__ilike='carol%')

to filter 'carol', 'Caroline', ...
is it possible?
## 

Vladimir

**Comment by hmarr** [comment]
MongoDB supports querying with regexes so try using

```
import re
Class.objects(name=re.compile(r'^carol', re.I))
```

Hope this does the trick

**Comment by dvv** [comment]
I added ilike to OPERATORS of Q class (also need to set it as valid at _transform_query):
        'ilike': 'this.%(field)s.toLowerCase().indexOf(%(value)s.toLowerCase()) != -1',

now Class.objects(Q(name__ilike='carol')) works.

However, how does it impact efficiency, for a strong precaution reads: " Only use these advanced queries if absolutely necessary as they will execute significantly slower than regular queries. This is because they are not natively supported by MongoDB – they are compiled to Javascript and sent to the server for execution."

My objective is to map URL parameters to efficient filtering criteria for QuerySet.
Can I convince you to add support for matching to mongoengine?

## Best regards,

Vladimir

**Comment by hmarr** [comment]
The `Q` object solution would work, but it would be slower as `Q` objects are translated to Javascript `$where` clauses, which aren't as quick as regular queries. What's wrong with using regular expressions? They're not too bad on efficiency (see http://www.mongodb.org/display/DOCS/Advanced+Queries#AdvancedQueries-RegularExpressions). Is what you're looking for an operator called `ilike` that is basically a shortcut for a regex (and compiles down to a regex behind the scenes)?

**Comment by dvv** [comment]
Exactly. The operator can be called, say, _match_, and should _not_ anchor to beginning or ending of the string:
Class.objects(name=re.compile(r'carol', re.I))

Would you take care?

**Comment by hmarr** [comment]
I think the best bet would be to emulate Django's behaviour, having `contains`, `icontains`, `startswith`, `istartswith`, `endswith`, and `iendswith`. The benefit of including anchoring versions is that MongoDB can still use indexes when the match is anchored to the start of the string (in the case sensitive version).

**Comment by dvv** [comment]
Agreed. Ping me when it will be OK, please.

TIA,
-- Vladimir
