### ISSUE TITLE
OperationalFailure when replica set's primary changed

### ISSUE THREAD

**Issue by observerss** [hmarr/mongoengine#267]
When replica set's PRIMARY changed, the mongoengine's cursor does not auto reloaded. So:

1.An OperationalFailure will be throwed when you do a new query
2.If you query again, everything works again(I guess that's pymongo's auto reconnect mechanism)

my ugly workaround:

add a decorator like this:
def auto_reload(func):
    try:
        return func
    except Exception:
        return func

add this decorator to every views in the django project

**Comment by rozza** [comment]
any idea if it is the mongoengine connection or pymongo's?

**Comment by rozza** [comment]
This should be fixed in dev as we no longer cache connections and just use the pymongo pool.
