### ISSUE TITLE
QuerySets evaporate on successive iteration

### ISSUE THREAD

**Issue by eykd** [hmarr/mongoengine#27]
`mongoengine.__version__ == '0.2.2'`

You can only iterate over a QuerySet once, and you'd better well have gotten what you needed! Expected behavior would be for the QuerySet to cache its results and remain stable over the lifetime of the object.

A sample session:

```
In [25]: docs = Foo.objects()

In [26]: list(docs)

Out[26]: [<Foo: Foo object>]

In [27]: list(docs)

Out[27]: []

In [28]: list(docs)

Out[28]: []

In [29]: print docs
-------> print(docs)
---------------------------------------------------------------------------
InvalidOperation                          Traceback (most recent call last)

/<ipython console> in <module>()

/lib/python2.6/site-packages/mongoengine/queryset.pyc in __repr__(self)
    598
    599     def __repr__(self):
--> 600         data = list(self[:REPR_OUTPUT_SIZE + 1])
    601         if len(data) > REPR_OUTPUT_SIZE:
    602             data[-1] = "...(remaining elements truncated)..."

/lib/python2.6/site-packages/mongoengine/queryset.pyc in __getitem__(self, key)
    351         if isinstance(key, slice):
    352             try:
--> 353                 self._cursor_obj = self._cursor[key]
    354             except IndexError, err:
    355                 # PyMongo raises an error if key.start == key.stop, catch it,


/lib/python2.6/site-packages/pymongo/cursor.pyc in __getitem__(self, index)
    220           - `index`: An integer or slice index to be applied to this cursor
    221         """
--> 222         self.__check_okay_to_chain()
    223         if isinstance(index, slice):
    224             if index.step is not None:

/lib/python2.6/site-packages/pymongo/cursor.pyc in __check_okay_to_chain(self)
    155         """
    156         if self.__retrieved or self.__id is not None:
--> 157             raise InvalidOperation("cannot set options after executing query")
    158
    159     def limit(self, limit):

InvalidOperation: cannot set options after executing query
```

**Comment by iapain** [comment]
+1 we solved this problem by adding cache in queryset.

**Comment by hmarr** [comment]
There has been a discussion about this at http://groups.google.co.uk/group/mongoengine-dev/browse_thread/thread/b75fdfaed1440997 - a concern is that documents can get pretty large (especially when you got lots of embedded document), so caching by default could be a memory hog. It seems like the most popular option would be to cache by default, but make it easy to disable the caching behaviour, like Django does.

**Comment by iapain** [comment]
You'r right about memory hog and since its mongo untill and unless there are lots of DBRef query read should be pretty similar to memcached read. Anyways there is always a work around by calling `list()` on queryset but then we lost Queryset method chainging on it and its not a recommended way.

@eykd try:
`docs = list(Foo.objects())`

**Comment by eykd** [comment]
The memory concerns make perfect sense, but since you're trying to mimic Django's QuerySet behavior and interface, the current behavior breaks the Principle of Least Surprise. This crucial difference should at least be clearly documented. It's not a completely foreign concept at least--mongoengine's QuerySets are to Django's as generator comprehensions are to list comprehensions. As long as the behavior is documented, then it's no more surprising than a generator "evaporating" after the first evaluation.

Also, something should be done about that exception. If it's going to act like a generator, it should merely evaporate, not explode. :)
