### ISSUE TITLE
subclasses not returned by MongoEngine

### ISSUE THREAD

**Issue by aid** [hmarr/mongoengine#271]
# Issue

When,
1.  inherited MondoEngine Documents are created in Django along the following form,
   
   base.models.py:
   
   ```
   class Company(Document):
     pass
   ```
   
   customer.models.py:
   
   ```
   class Customer(Company):
     pass
   ```
2. Customer objects are added into MongoDB.
3.  One tries to retrieve these Customer objects, when referencing them as their base Class without specifically importing the child model.

An Exception is raised rather than the Customer class being returned.
# Demonstration

```
$ ./manage.py shell
>>> from base.models import *
>>> cust1 = Company.objects.get(name='Customer1')
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/usr/local/Cellar/python/2.7/lib/python2.7/site-packages/mongoengine-0.4-py2.7.egg/mongoengine/queryset.py", line 724, in get
    return self[0]
  File "/usr/local/Cellar/python/2.7/lib/python2.7/site-packages/mongoengine-0.4-py2.7.egg/mongoengine/queryset.py", line 1026, in __getitem__
    return self._document._from_son(self._cursor[key])
  File "/usr/local/Cellar/python/2.7/lib/python2.7/site-packages/mongoengine-0.4-py2.7.egg/mongoengine/base.py", line 692, in _from_son
    """.strip() % class_name)
NotRegistered: `Company.Customer` has not been registered in the document registry.
                        Importing the document class automatically registers it,
                        has it been imported?
```
# Workaround

By importing the module that defines the Customer class; the correct object is returned,

```
>>> from customer.models import *
>>> cust1 = Company.objects.get(name='Customer1')
>>> cust1
<Customer: Customer1>
```

The modules defining more specific objects should not need to be included - this is to allow a generic programming methodology.
# Resolution

MongoEngine maintains a registry of all Document classes; this should be consulted when an object is to be returned - using the get_document() function defined in base.py to find the correct class allowing the proper object to be returned to the caller without the need for importing extra modules.
# Diff

The following diff resolves the issue.

```
diff --git a/mongoengine/base.py b/mongoengine/base.py
index 8d0c470..1d72055 100644
--- a/mongoengine/base.py
+++ b/mongoengine/base.py
@@ -681,16 +681,7 @@ class BaseDocument(object):

         # Return correct subclass for document type
         if class_name != cls._class_name:
-            subclasses = cls._get_subclasses()
-            if class_name not in subclasses:
-                # Type of document is probably more generic than the class
-                # that has been queried to return this SON
-                raise NotRegistered("""
-                        `%s` has not been registered in the document registry.
-                        Importing the document class automatically registers it,
-                        has it been imported?
-                    """.strip() % class_name)
-            cls = subclasses[class_name]
+            cls = get_document(class_name)

         present_fields = data.keys()
         for field_name, field in cls._fields.items():
```
# Confirmation

With the patch applied, the query works as expected - without raising an Exception,

```
$ ./manage.py shell
>>> from base.models import *
>>> cust1 = Company.objects.get(name='Customer1')
>>> cust1
<Customer: Customer1>
>>> 
```

**Comment by ultramiraculous** [comment]
This is a pretty big feature regression for two codebases I'm working with.  I know this is free software, but please watch out for changes like this in the future.  There wasn't a reason for the restriction to be added, and it worked fine in the past as a way to work with subclassed data.

**Comment by aid** [comment]
How did it break your code..?

**Comment by ultramiraculous** [comment]
The biggest one was a situation where I import, say, ScoreRecord, which is subclassed a few times and almost never used vanilla.  The main thing it adds is a .score property.  If we try to do a for loop like so:

total = 0
for rec in ScoringRecord.objects.filter(...):
     total += rec.score

Without the diff you posted, we'll get an import exception.  For this particular case, we're actually using .sum('score'), but there's other cases where we iterate through documents of a base class type which will now throw an error.  Basically there seems to be at least one place where I don't think I ever had a NoneType issue in the past, but I'm getting NotRegistered exceptions now.

**Comment by aid** [comment]
Ar, I think I understand now.

I don't think your problem is with the above diff that I proposed (that hasn't been integrated into this fork) but with a related commit made by rozza at a similar time,

https://github.com/hmarr/mongoengine/commit/1631788ab6bfe66779f226f750b9f235c1f6c7ea

...that raises an exception anther simply returning None when MongoEngine can't get hold of the real class that an object represents.

Niether of the above situations above are good in my opinion hence the above patch with actually returns the real object you're after rather than either silently failing (returning None) or raising an Exception.

Try applying the above patch and see if that solves the issues you have found.  If it does; let rozza know and with a little more pressure the above patch may get applied to this fork.

**Comment by ultramiraculous** [comment]
Yeah, the diff you proposed works great and does what I expected.  Sorry for the confusion.  Now I'm wondering if I was getting Nones and in the past and somehow didn't have a problem with it, but your diff has been working great.

**Comment by aid** [comment]
If you're getting the NotRegistered exceptions now; then I'm pretty sure you will have had Nones previously; with the code silently skipping over them - likely resulting in those 'sum' functions not really adding up all they should... 

Rozza, are you reading this?  Could you consider integrating this diff?

**Comment by rozza** [comment]
@aid all good - will add to the 0.6 release :)

**Comment by rozza** [comment]
now in dev!  Thanks @aid for the patch
