### ISSUE TITLE
Add field name to ValidationError messages

### ISSUE THREAD

**Issue by mattupstate** [hmarr/mongoengine#274]
It'd be nice to be able to get a reference to the field, at least the name, in the ValidationError messages

**Comment by n1k0** [comment]
+1

**Comment by linuxnow** [comment]
This is done in the dev branch, I think you should close this issue.

**Comment by rozza** [comment]
thanks all -  as @linuxnow said its in dev :)

**Comment by mattupstate** [comment]
Lovely!
