### ISSUE TITLE
Document : validate field clashes with validate method

### ISSUE THREAD

**Issue by llazzaro** [hmarr/mongoengine#275]
This is not neccesary a bug.

the Document uses self.validate() (mongoengine/document.py line 73) but this gives the following error :

**TypeError: 'bool' object is not callable**

if the model is like this one

```
class ModelExample(Document):
    validate = BooleanField(required=True,default=False)
```

I know change the booleanfield to valid or accepted, etc fixes the error. but this error cause me two days of #%#$%@#$  :)

**Comment by rozza** [comment]
Hi,

I think that has been fixed on the dev branch - can you confirm which branch you're using!

**Comment by llazzaro** [comment]
I checkout the dev branch, the error continues

**Comment by wpjunior** [comment]
"validate" is a method of Document Class.
please rename the attribute.

**Comment by rozza** [comment]
@llazzaro - I've added an InvalidDocumentError, which will help users debug errors like this much quicker.

**Comment by llazzaro** [comment]
great! :)
