### ISSUE TITLE
Queryset returns None for documents which inherit a class from another file

### ISSUE THREAD

**Issue by SeanOC** [hmarr/mongoengine#28]
Scenario:
- Create a document class called Person which inherits from mongoengine.Document in people/person.py.
- Create a document class called Employee which inherits from Person in people/employee.py.
- Create and save instances of both classes.
- Call Person.objects().  You will get back a queryset as expected but there will be a None value in place of each expected Employee instance.

I'll try to write up a test case to catch this soon.

**Comment by SeanOC** [comment]
UPDATE:  Apparently this only happens when the document classes live within different Django apps and Django code gets imported.  Something about what Django does to the import process/sys.path results in cls.**subclasses** to not report classes in other applications.

I'll try to dig into this more tomorrow and see what I can find.

**Comment by SeanOC** [comment]
UPDATE: The specific trigger is if you import the base class into the child class's module with a different path than where you use the base class for querying (i.e. my_project.app_a.documents vs. app_a.documents) cls.**subclasses** gets all confused.

I'm not sure if this is something which can/should be fixed or if this is something which should just be warned about in the documentation.

**Comment by hmarr** [comment]
When we added support for `GenericReferenceField`s, a [registry of documents](http://github.com/hmarr/mongoengine/blob/master/mongoengine/base.py#L8) was added. Maybe extending and using this, rather than `cls.subclasses` could help solve the problem - just a thought, no idea if it would actually work though.
