### ISSUE TITLE
if set field unique=True 

### ISSUE THREAD

**Issue by TeemoWan** [hmarr/mongoengine#280]
Exception Value:    

Tried to save duplicate unique keys (E11000 duplicate key error index: babelbook.user.$email_1  dup key: { : null })

Exception Location:     build/bdist.linux-i686/egg/mongoengine/document.py in save, line 183

Traceback:
File "/home/wanli/django/babelbook/lib/python2.7/site-packages/Django-1.3-py2.7.egg/django/core/handlers/base.py" in get_response
1.                         response = callback(request, _callback_args, *_callback_kwargs)
   File "/home/wanli/django/babelbook/lib/python2.7/site-packages/Django-1.3-py2.7.egg/django/utils/decorators.py" in _wrapped_view
2.                     response = view_func(request, _args, *_kwargs)
   File "/home/wanli/django/babelbook/babelbook/apps/people/views.py" in register
3.             new_user = form.save(request=request)
   File "/home/wanli/django/babelbook/babelbook/apps/people/forms.py" in save
4.         new_user = User.create_user(username=self.cleaned_data['username'], password=self.cleaned_data['password1'], email=self.cleaned_data['email'])
   File "/home/wanli/django/babelbook/babelbook/apps/people/models.py" in create_user
5.         user.set_password(password)
   File "/home/wanli/django/babelbook/babelbook/apps/people/models.py" in set_password
6.         self.save()
   File "build/bdist.linux-i686/egg/mongoengine/document.py" in save
7.             raise OperationError(message % unicode(err))

Exception Type: OperationError at /people/register/
Exception Value: Tried to save duplicate unique keys (E11000 duplicate key error index: babelbook.user.$email_1  dup key: { : null })

**Comment by TeemoWan** [comment]
mongoengine version 0.5 
mongodb 1.6.3

**Comment by rozza** [comment]
Hi,

Not sure how I can replicate - can you provide more details :)

**Comment by dcrosta** [comment]
@wanli2011, mongodb treats missing values as `null` for the sake of unique indexes. Thus if you have declared a field to be `unique=True`, then at most one document can be missing a value for that field (or have a value of `null`/`None` explicitly set for that field).

If you want the uniqueness applied only on documents that have a value set for that field, you can use a sparse index. You can create one with:

```
meta = {
    'indexes': [
        {'fields': ['your_field'], 'sparse': True, 'unique': True},
    ]
}
```

Using this method, you should _not_ specify `unique=True` in your field definition. Also note that MongoDB has a limitation that sparse indexes can only index one field.

**Comment by TeemoWan** [comment]
Thanks, no errors, I forgot to update the index
