### ISSUE TITLE
item frequencies falls in this Test Case

### ISSUE THREAD

**Issue by wpjunior** [hmarr/mongoengine#286]
test case:

``` python
from mongoengine import *
connect('test')

class Data(EmbeddedDocument):
    name = StringField()

class Extra(EmbeddedDocument):
    tag = StringField()

class Person(Document):
    data = EmbeddedDocumentField(Data, required=True)
    extra = EmbeddedDocumentField(Extra)

Person.drop_collection()

p = Person()
p.data = Data(name="Wilson Jr")
p.save()

p = Person()
p.data = Data(name="Wesley")
p.extra = Extra(tag="friend")
p.save()

print Person.objects.item_frequencies('extra.tag')
```

**Comment by julienr** [comment]
I think this is related to #285, which includes an explanation and a quick hack to fix it.

**Comment by wpjunior** [comment]
i think the bug is located in the lines:
https://github.com/hmarr/mongoengine/blob/master/mongoengine/queryset.py#L1529
https://github.com/hmarr/mongoengine/blob/master/mongoengine/queryset.py#L1575
https://github.com/hmarr/mongoengine/blob/master/mongoengine/queryset.py#L1591

**Comment by wpjunior** [comment]
pull request: https://github.com/hmarr/mongoengine/pull/287

**Comment by rozza** [comment]
All merged thanks @wpjunior
