### ISSUE TITLE
Auto-Dereferencing Bug?

### ISSUE THREAD

**Issue by adamaflynn** [hmarr/mongoengine#289]
I'm trying to upgrade to mongoengine 0.5 and it looks like there are some pretty serious bugs with the way auto-dereferencing is interacting with my setup. The docs are light on details for the specifics of how auto-dereferencing should behave, so I'm not sure if this behaviour is to spec or a bug, but, it feels like a bug.

I'm having a tough time isolating exactly what's going on (feel free to ping me for more details), but an AJAX operation that used to be 30 queries jumped to 322 from all the auto-derferencing. If I comment out reset_changed_fields() and the "Save any references / generic references" block, I can get that down to ~100 queries.

Doing a save() on a DiscussionParticipant object (which maps Users <=> Discussions and stores some meta data about the user's state in a discussion), with a single changed, non-reference field executes 57 MongoDB queries. It's difficult to parse through exactly what each one is doing, but the first 10 or so I looked at seemed to first do a $set on the changed field (as expected) then they were loading the User associated with the DiscussionParticipant, then loading all of the reference lists associated with that user. 

Then it loads the full discussion and seems to load all of the users involved in the discussion. After that, it tries to atomically set values in 2 unrelated fields (the user's interests and the discussion's comments; comments are updated twice [possibly related to me using an atomic operation to add the comment and this trying to do a cascading save?], user's interests are never touched). 

It also tries to load objects by IDs from other collections (loading DiscussionParticipants in a sequence of IDs with an interest ID mixed in there).

So -- I'm not sure what's going on here; it could just be the way I've denormalized the data interacting strangely with mongoengine, but it feels like there are definitely bugs here (e.g. writing to unchanged fields, fetching using IDs from the wrong collection). If I can help debug this, let me know (feel free to catch me on e-mail/gtalk at adam@contextlogic.com)... I don't mind spending some time trying to fix the bug, but I need some direction on what the expected behaviour is.

**Comment by rozza** [comment]
Hi Adam,

Sounds like a bug to me, definitely not whats intended by dereferencing.  It would be interesting to get a test case so I can replicate and track it down and look to improve this.  Could you message me the schema you are using?

Ross

**Comment by adamaflynn** [comment]
Ross,

I'll see what I can do about distilling down a minimal schema that
duplicates this bug to work from.

Also - Can you give me a run-down of what the intended semantics of
the auto-dereferencing (both for loading and saving) are so that I can
continue to investigate on my own?

Adam

On Fri, Sep 23, 2011 at 12:05 AM, Ross Lawley
reply@reply.github.com
wrote:

**Comment by rozza** [comment]
Hi,

Dereferencing is supposed to improve upon the pervious behaviour of dereferencing which caused a query for every DBRef.  It now loops through data structures (up to a certain depth) and collates all the DBRefs and then queries the database with the minimum number of queries. 

Well thats the theory, but that doesn't seem to be happening in your case - there are tests for dereferencing: https://github.com/hmarr/mongoengine/blob/dev/tests/dereference.py so any new test cases would be ideal.

Also, there are cascading saves now as well, so if you change an object and it has a DBRef that has been changed then that  object will also be saved..

So, I'm wondering, if there is a recursion issue with DBRefs objects containing more DBRefs and recursive dereferencing racking up queries and not being efficient.  Also, perhaps saves are cascading and saving the same DBRef'd objects.

Lets see if we can get a testcase and look at improving how it works / adding finer grained control.  There has already been talk on the developer list about adding cascading save control.

Ross

**Comment by adamaflynn** [comment]
Hi,

Yeah, my thinking is similar. The way this particular schema is laid
out leads to some pretty nasty circular references that could expose
problems if there's a bug in the halting condition of the recursion.

I'll do some more digging for a solution and try to find a simple test
case that breaks.

Adam

On Fri, Sep 23, 2011 at 12:36 AM, Ross Lawley
reply@reply.github.com
wrote:

**Comment by jensimik** [comment]
would be great if there would be an option on the document to disable this auto-dereferencing code - it takes huge amounts of time for my usage (i don't use any dbref's - and have complex/large dict structures - which suddenly started to take several seconds to load)

**Comment by rozza** [comment]
@jensimik - shouldnt be a problem - will hopefully fix that and this issue in 0.6

**Comment by rozza** [comment]
This should now be much better as max depth is now honoured for dicts / lists.

@jensimlk - If you feel its still too slow as you have no dereferences at all - then please open another ticket.  Dereferencing / Custom lists / dicts are used for auto delta'ing changes.  So we could in theory turn that off but you'd have to manually manage updates.
