### ISSUE TITLE
Support storing files in GridFS

### ISSUE THREAD

**Issue by benmur** [hmarr/mongoengine#29]
To support large blobs that would not be suitable for a BinaryField, a FileDocument or EmbeddedFileDocument could be needed, that would be backed by GridFS.

If this is interesting for MongoEngine, I might take a shot at implementing it, since I need it for a project of mine.

**Comment by hmarr** [comment]
This is definitely a future aim for MongoEngine - I'm not sure about the best way of implementing this in terms of the root collections, listing files, etc. but I'd be really interested in hearing your ideas, and if you fancy getting started on it, that would be great.
Cheers,
Harry

**Comment by benmur** [comment]
The way I see it, to keep the API simple and consistent, is to have a new document type, that inherits from Document. Documents of a particular type/collection can then be listed as normal documents, or queried just as simply as a Document (although the querying part may need a specialized QuerySet implementation).

The most simple usage of the API for the user could be:

```
class RandomAttachment(FileDocument):
    pass

class UserPhotoAttachment(FileDocument):
    owner = ReferenceField(User, required=True)

def read_then_delete_user_photo(user):
    photo = UserPhotoAttachment.objects.get(owner=user)
    f = photo.open(r)
    data = f.read()
    f.close()
    photo.delete() # next call to read_then_delete_user_photo won't work
    return data

def delete_big_attachments():
    big_attachments = RandomAttachment.objects(size__gt=20000000)
    for a in big_attachments:
        a.delete()
```

with FileDocument problably looking like this:

```
class FileDocument(Document):
    __metaclass__ = FileDocumentMetaclass

    # QuerySetManager set by the metaclass
    # can process queries on size, content_type and filename
    objects = GridFSQuerySetManager()

    # some pre-defined properties
    # Not really fields, since they proxy the fields in
    # the GridFile metadata
    filename = property(...)
    content_type = property(...)
    size = property(...)
    md5 = property(...)

    # some more fields
    creation_date = DateTimeField(...)

    def open(self, mode):
        """Returns a file-like object
        """
        pass

    # custom implementation of .save()
    def save(self): pass

    # custom implementation of .save()
    def delete(self): pass

    def __enter__(self):  # can act as a context manager
        pass

    def __exit__(self, ...): # can act as a context manager
        pass
```

It could also be nice (for later) to offer a django view for file download (with parameterizable user-implemented permission manager and permalink generator).

Do you have any comments ? If this design looks ok to you, I'll start coding.

Cheers,

Rached

**Comment by hmarr** [comment]
Looks great, really like the consistency with the rest of the API. I guess one important thing is that the files may be referenced from regular documents. Also, do you reckon it is worth letting users specifying the root collection they want to use (or taking it from the name of the `FileDocument` sublcass), or will just using `fs` be sufficient?

Cheers,

Harry

**Comment by benmur** [comment]
Of course it is important that files can be referenced from other documents --- this is how I would like to use it in the application I am developing.

Also, I think that letting users choose the root collection's name is important, as well as having multiple root collections available for GridFS objects --- two features we get for free by making the collection name from the `FileDocument` subclass. It can make querying/management/administration of the database easier, while not making code more difficult to write for users; in fact the similarity can be a benefit, following the principle of least surprise compared to regular collections.

One thing that I'm still not sure about is if we want to allow creating direct instances of `FileDocument`. This seems to not be supported for regular `Document`s and I think it should be the same for `FileDocument`s.

I'll start some code soon.

Rached

**Comment by iapain** [comment]
Truefuly, I'd not bother about `FileDocument`. I'd rather opt for a `FileField` with a backend option which would be either `GridFS` or `LocalFS`. Also `FileField` would inherit `DictField` to keep file metadata.

`FileDocument` would makes things api more complicated which should be avoided.

**Comment by flosch** [comment]
I committed a version of a FileField and GridFS-Proxy (thanks to schallis) which is already in v0.4 branch and works pretty well for me: http://github.com/hmarr/mongoengine/commit/0512dd4c25e0f8395c317725fa149a64025faf3e

I think it would be nice if we make the FileField's backend exchangeable (e. g. GridFS, LocalFS, AmazonS3FS, ...) via an argument or so.

**Comment by benmur** [comment]
I took a quick look at 0512dd4c25e0f8395c317725fa149a64025faf3e and I think it looks nice. The API fits my initial use case and the prototype code I had but did not have the time to publish. I'll get away with querying by storing some metadata aside.

Nice work !

**Comment by iapain** [comment]
Code looks nice but I'll urge to keep `GridFSProxy` consistent with DjanoStorage API. It'll be very useful IMO. Also, `FileField` should accept backend if absent then it make sense to assume `GridFSProxy`

**Comment by hmarr** [comment]
I'm closing this as it works in v0.4, but I'd like to see some Django integration in future versions.
