### ISSUE TITLE
QuerySet.get is inefficient

### ISSUE THREAD

**Issue by colinhowe** [hmarr/mongoengine#290]
Hello,

Just looking through some query logs and spotted that .get does a count and then a fetch. That's two queries (and the unlimited count _could_ take a long time). Can we change this to do a fetch for two items and then if two are found it should fail, if one is found it should succeed, if none found it should fail too.

Happy to code it up and submit a patch.

**Comment by rozza** [comment]
Sounds good to me

**Comment by rozza** [comment]
Thanks @paulcunnane this is now in dev
