### ISSUE TITLE
Recursive Use of force_insert Causes Issues with References

### ISSUE THREAD

**Issue by mankyd** [hmarr/mongoengine#295]
Define a document that has ReferenceFields to other objects. Try to create a new instance of that Document, giving it references to existing objects. If that instance is saved with force_insert=True, it will try to force_insert all of its references as well which causes duplicate key errors. There needs to be a way to only force_insert the main instance.

**Comment by rozza** [comment]
Thanks - will look into it.

**Comment by rozza** [comment]
@mankyd added cascade_kwargs to the dev branch, which allows you to override any set kwargs to save.  See the diff / testcase for more detail!
