### ISSUE TITLE
Provide the option of not using auto-dereferencing for ReferenceField

### ISSUE THREAD

**Issue by alup** [hmarr/mongoengine#31]
Currently, ReferenceField is automatically dereferenced. It would be nice if there was the option of not using this mechanism.

BTW, good job :)

**Comment by mattdennewitz** [comment]
The actual `DBRef` is available via a `Document` instance's `_data` attribute.

```
from pymongo.dbref import DBRef
from mongoengine import *


connect("testdb")

class Artist(Document):
    name = StringField()

class Album(Document):
    title = StringField()
    artist = ReferenceField(Artist)


beck = Artist(name="Beck")
beck.save()

odelay = Album(title="Odelay", artist=beck)
odelay.save()

# grab odelay from the db
odelay = Album.objects().first()

assert isinstance(odelay._data['artist'], DBRef)

Artist.drop_collection()
Album.drop_collection()
```

**Comment by mattdennewitz** [comment]
that said, perhaps it's worth looking into a `dereference` method to favor manual dereferencing.

**Comment by alup** [comment]
The idea is to provide the ReferenceField, a param, something like ReferenceField(model_name, auto_dereference=True), so the user will be able to use the auto_dereference=False.

This is helpful, if for example I want to get a Document which contains references to other documents and I don't like to load everything in memory.

**Comment by mattdennewitz** [comment]
i like the idea of the `auto_dereference` argument. 

loading a document with `ReferenceField`s doesn't mean they'll all be automatically dereferenced. the actual dereferencing happens when you first access the field.

**Comment by amcgregor** [comment]
+5

I have a CMS that stores parent/child relationships in a fairly complicated manner, and auto-dereferencing increases my query count (and execution time) substantially.  (Enough to notice.)

Specifically, an individual Asset subclass instance contains:
1. An ObjectID
2. A generic reference to its parent.
3. A list of generic references to its ancestors, in order.
4. A list of generic references for its immediate children, if any.
5. A large amount of additional data.

For a Folder(Asset) with ~100 items, one level deep, the number of generic references is greater than 400, and simulating a tree structure this way I'm worried about loading the entire tree each time a single Asset subclass instance is loaded.  :/

I propose a common argument for all fields, `lazy`, which tells MongoEngine to use a default set of fields to a `.only(…)` call internally, then load the additional data when accessed.  (Vs. the current behaviour of returning the default value for fields excluded by `.only(…)`.)

**Comment by rozza** [comment]
Is this still an issue?  As far as I can tell `ReferenceField` are lazyily dereferenced.
