### ISSUE TITLE
Upgrade mongoengine from 0.4 to 0.5. Queryset always return empty list

### ISSUE THREAD

**Issue by kenshinx** [hmarr/mongoengine#310]
I have upgrade mongoengine from 0.4 to 0.5  in  my project. But the queryset always return empty list.
such as:

> > > Foo.objects.all()
> > > []
> > > When i revert  the mongoengine version from 0.5 to 0.4. All  issues resolved
> > > Foo.objects.all()
> > > [<Foo: Foo object>, <Foo: Foo object>]

The  development environment.Python V2.6.5 ,Django V1.3.0, pymongo V2.0.1
The django settings.py related  mongoengine:
connect('rs', host= ['10.1.1.60','10.1.1.61','10.1.1.62'], port=27017)

I'm not sure there is bug here. but I hope can get some direction or sugesstion

Thanks

kenshin

**Comment by rozza** [comment]
Hi please check out the docs:  http://mongoengine.org/docs/v0.5/upgrade.html?highlight=upgrade#to-0-5

That should get you on your way!
