### ISSUE TITLE
Accessing "pk" raises an error

### ISSUE THREAD

**Issue by jpfarias** [hmarr/mongoengine#315]
Hi!

It is probably not good practice, but trying to access "pk" on a EmbeddedDocument raises KeyError: 'id_field'.

Perhaps this should be fixed.

I run into this error when I tried to do `[getattr(obj, fieldname) for fieldname in dir(obj) if not fieldname.startswith('_')]` which might be a real use case. I fixed with a work around by adding `and fieldname not in ('pk', 'validate', 'to_mongo')` to the condition.

Got that error on mongoengine 0.4, not sure if that was fixed on 0.5 already.

**Comment by rozza** [comment]
Fixed in dev
