### ISSUE TITLE
Wrong collection name after upgrade to 0.5

### ISSUE THREAD

**Issue by tomekwojcik** [hmarr/mongoengine#319]
Hi guys,
I encountered a strange problem.

I have a class:

```
class IPAddress(Document):
    # CODEZ IZ HERE
```

and with MongoEngine 0.4 it was tied to `ipaddress` collection. With 0.5 however it's tied to `i_p_address` though the docs state that the collection name will by default be the lowercase class name. Adding `meta = { 'collection': 'ipaddress' }` fixed this, of course.

Now, either I'm wrong or the docs are wrong :).

**Comment by ultramiraculous** [comment]
As of .5 it seems to be converting camelcase to underscores, rather than just lowercase.  In my case I had GameData, which became game_data, instead of gamedata.  There didn't seem to be any notice of this in the changelog.

**Comment by rozza** [comment]
See: http://mongoengine.org/docs/v0.5/upgrade.html
