### ISSUE TITLE
Denormalized fields

### ISSUE THREAD

**Issue by Soviut** [hmarr/mongoengine#32]
ReferenceFields and EmbeddedDocumentFields should allow for a list of denormalized sub-fields.  By this, I mean it should be possible to store additional fields alongside the ID.

For example, if I have an author ReferenceField that points to a User document, I may want to be able to denormalize the user's name into the reference field so that it can be returned more quickly without needing to dereference.  Naturally, trying to retrieve any fields that aren't denormalized would result in a full dereference of the referenced document.

One of the benefits of doing this formally through a field is that when updates are made, they can be propagated to both the denormalized sub-fields and the referenced document.

**Comment by rozza** [comment]
Any proposals / ideas on how you'd implement this?  Even if its just syntax of declaring it...

**Comment by rozza** [comment]
Signal support can handle the denormalizing, closing ticket for now if a concrete implementation is proposed will review then
