### ISSUE TITLE
thread identity error in python 2.5

### ISSUE THREAD

**Issue by cman122887** [hmarr/mongoengine#321]
def get_identity():
"""
Creates an identity key based on the current process and thread identity.
"""
    identity = multiprocessing.current_process()._identity
    identity = 0 if not identity else identity[0]

```
identity = (identity, threading.current_thread().ident)
return identity
```

on 2.5 this error pops up
# AttributeError: '_MainThread' object has no attribute 'ident'

import thread
thread.get_ident() 

works though

they deprecated thread for threading but threading did not have a main thread identity till 2.6

**Comment by rozza** [comment]
Hi as pymongo has its own threadpooling I've removed this in dev branch as part of the multidb support.
