### ISSUE TITLE
improvement Adding $pop update modifier?

### ISSUE THREAD

**Issue by GermanoGuerrini** [hmarr/mongoengine#33]
Adding 'pop' at http://github.com/hmarr/mongoengine/blob/master/mongoengine/queryset.py#L644 should be enough.
In pymongo {'$pop': {'list_field_name':1}} works flawlessly.

**Comment by benhodgson** [comment]
Support for this would be very well received by me — I have to manually write many of my updates in exec_js at the moment.

**Comment by richardhenry** [comment]
+1!

**Comment by richardhenry** [comment]
I've made this change in http://github.com/richardhenry/mongoengine and sent hmarr a pull request.

**Comment by hmarr** [comment]
richardhenry: cheers for that, merged it in to 0.4

**Comment by benhodgson** [comment]
richardhenry, hmarr: Thank you! Do you have an ETA on 0.4’s release?

**Comment by hmarr** [comment]
benhodgson: We've got a few more small issues to iron out, and a couple more smallish features to add, so hopefully within a week or so. Having said that, 0.4 isn't that unstable so you could use it now (pip install -e git+git://github.com/hmarr/mongoengine@v0.4#egg=mongoengine)...
