### ISSUE TITLE
Add Django-like QuerySet Proxies and more exceptions

### ISSUE THREAD

**Issue by m-bd** [hmarr/mongoengine#34]
Hi hmarr and all contributors !

Can you add QuerySet proxies and raise more exceptions like Django ?
It would be nice if MongoEngine works as a django.db backend.

Thanks!

**Comment by iapain** [comment]
Exceptions should be django like. +1

**Comment by hmarr** [comment]
We're trying not to couple ourselves to a specific framework. Despite the obvious API similarities between Django and MongoEngine, we don't want to introduce Django as a dependency of MongoEngine - I know of a few people using MongoEngine in production with other frameworks.

Something that has been mentioned a few times is moving the Django-related code from MongoEngine into a separate 'glue' project that would also provide adaptors for the Django API, raise Django exceptions, (provide a django.db backend?), etc.

There is some great work on Django integration going on in a fork at http://github.com/aparo/mongoengine

Cheers,

Harry

**Comment by iapain** [comment]
@harry: your justification makes sense but i still see but point is not Django Exceptions. Currently `DoesNotExist` Exception needs to be imported everywhere and its not documented well. IMO we should raise `Document.DoesNotExit` as subclass of `DoesNotExist` Exception. Idea is to contribute `DoesNotExist` exception to `Document` class.

Cheers,
D

**Comment by hmarr** [comment]
Ah right, yea that makes sense to me.

Harry

**Comment by iapain** [comment]
Implemented. `DoesNotExist` and `MultipleObjectsReturned` now contributes to Document base class. Old version still works so

```
try:
    Person.objects.get(name='name that doesnot exist')
except Person.DoesNotExist:
    print "catch"`
```

and

```
try:
   Person.objects.get(name='name that doesnot exist')
except DoesNotExist:
    print "catch"
```

Both works

**Comment by hmarr** [comment]
Cheers, I've merged this in.

**Comment by m-bd** [comment]
Thank you ! :-)
