### ISSUE TITLE
can't have 2 special fields

### ISSUE THREAD

**Issue by maxcountryman** [hmarr/mongoengine#343]
I'm getting an error when trying to filter a query by two GeoPointFields as `Ride.objects(Q(orig__within_distance=orig_point_and_dist) & Q(dest__within_distance=dest_point_and_dist))`. This is related to my previous issue but now the issue is either related directly to pymongo or the way pymongo is being interfaced.

Here's the error:

OperationFailure: command SON([('count', u'ride'), ('query', {'dest': {'$within': {'$center': [[47.6062095, -122.3320708], 0.5]}}, '_types': 'Ride', 'orig': {'$within': {'$center': [[47.6587802, -117.4260466], 0.5]}}}), ('fields', None)]) failed: exception: can't have 2 special fields

**Comment by maxcountryman** [comment]
whoops, apparently this works: `Ride.objects(Q(orig__within_distance=orig_point_and_dist) and Q(dest__within_distance=dest_point_and_dist))`

**Comment by maxcountryman** [comment]
I'll have to take that back, while logical and does work, I actually need to use & as you would with other queries. Any thoughts?

**Comment by rozza** [comment]
Hi @maxcountryman unfortunately this isnt currently supported by mongodb

**Comment by maxcountryman** [comment]
Thanks for the follow up. That's unfortunate. I had talked with some of the devs at 10gen and they've said as much. It sounds like they're hoping to support it eventually. I wonder if they ran into a technical limitation or just didn't have time to implement?
