### ISSUE TITLE
Embedded Documents & Editing

### ISSUE THREAD

**Issue by zenom** [hmarr/mongoengine#35]
So I have a document called program. Inside there I have an embedded 
document called sites.  The sites document consists of 4 fields (tags, 
slug, url, name). 

So a program can have multiple sites and I want to be able to delete 
one site from that program.  The command to do this via the mongo 
console is: 
## working command

`db.program.update({"slug": "test-program"}, {$pull: {"sites": {"slug": 
"site-1"}}})`

I tried to run the following: 

`Program.objects(slug="test-program").update(pull__sites__slug=slug)`

Doing a print on the update method in mongo engine basically produced the following
`db.projects.update({"slug": "test-program"}, {$pull: {"sites.slug": "site-1"}})`
## the model

`class PaySite(EmbeddedDocument): 
    """Represents a paysite, for a program.""" 
    name = StringField(required=True) 
    slug = StringField(required=True) 
    url = URLField(required=True, verify_exists=True) 
    tags = ListField(StringField(required=True)) 
    date_created = DateTimeField(default=datetime.datetime.utcnow) 

class Program(Document): 
    name = StringField(required=True) 
    url = URLField(required=True) 
    affiliate_id = StringField(required=True) 
    active = BooleanField(required=True, default=True) 
    slug = StringField(required=True) 
    deleted = BooleanField(default=False) 
    date_created = DateTimeField(default=datetime.datetime.utcnow) 
    sites = ListField(EmbeddedDocumentField(PaySite)) `

Being able to query the embedded document somehow, to provide the new paysite object to the program object, or a way to modify embedded documents directly would be nice.

**Comment by rozza** [comment]
This has been fixed in dev!

**Comment by rozza** [comment]
Hold the bus!  I may have been to hasty there - adding regression test.
