### ISSUE TITLE
Things for 0.6

### ISSUE THREAD

**Issue by rozza** [hmarr/mongoengine#368]
- Add documentation regarding max_depth / select_related
- Add some documentation for cascading saves (#370)

**Comment by wpjunior** [comment]
we are already close to releasing version 0.6?

**Comment by rozza** [comment]
Yes!  Nothing major left todo!

2011/12/7 Wilson Jnior <
reply@reply.github.com

**Comment by kolanos** [comment]
Is #398 holding up 0.6's release?

**Comment by rozza** [comment]
So close now
