### ISSUE TITLE
InvalidDocument raised when attempting to save a decimal.Decimal instance in a DecimalField

### ISSUE THREAD

**Issue by donspaulding** [hmarr/mongoengine#37]
In [1]: import decimal, mongoengine

In [2]: class MyDoc(mongoengine.Document):
   ...:     f1 = mongoengine.DecimalField()
   ...:    

In [3]: doc = MyDoc(f1=decimal.Decimal("1.50"))

In [4]: doc.validate()

In [5]: doc.save()
/Users/don/Development/python/virtualenvs/bloono/lib/python2.6/site-packages/pymongo/collection.py:246: RuntimeWarning: couldn't encode - reloading python modules and trying again. if you see this without getting an InvalidDocument exception please see http://api.mongodb.org/python/current/faq.html#does-pymongo-work-with-mod-wsgi
##   message.insert(self.__full_name, docs, check_keys, safe), safe)

InvalidDocument                           Traceback (most recent call last)

/Users/don/Development/python/bloono/<ipython console> in <module>()

/Users/don/Development/python/virtualenvs/bloono/lib/python2.6/site-packages/mongoengine/document.pyc in save(self, safe, force_insert)
     76                 object_id = collection.insert(doc, safe=safe)
     77             else:
---> 78                 object_id = collection.save(doc, safe=safe)
     79         except pymongo.errors.OperationFailure, err:
     80             message = 'Could not save document (%s)'

/Users/don/Development/python/virtualenvs/bloono/lib/python2.6/site-packages/pymongo/collection.pyc in save(self, to_save, manipulate, safe)
    204 
    205         if "_id" not in to_save:
--> 206             return self.insert(to_save, manipulate, safe)
    207         else:
    208             self.update({"_id": to_save["_id"]}, to_save, True,

/Users/don/Development/python/virtualenvs/bloono/lib/python2.6/site-packages/pymongo/collection.pyc in insert(self, doc_or_docs, manipulate, safe, check_keys)
    244 
    245         self.__database.connection._send_message(
--> 246             message.insert(self.__full_name, docs, check_keys, safe), safe)
    247 
    248         ids = [doc.get("_id", None) for doc in docs]

InvalidDocument: Cannot encode object: Decimal('1.50')

In [6]: mongoengine.VERSION
Out[6]: (0, 3, 0)

In [7]: mongoengine.connection._connection.server_info()
Out[7]: 
{u'bits': 64,
 u'gitVersion': u'514f8bbab657c1dc110d45eea6ea33de296dbb26',
 u'ok': 1.0,
 u'sysInfo': u'Darwin erh2.10gen.cc 9.6.0 Darwin Kernel Version 9.6.0: Mon Nov 24 17:37:00 PST 2008; root:xnu-1228.9.59~1/RELEASE_I386 i386 BOOST_LIB_VERSION=1_37',
 u'version': u'1.4.0'}

**Comment by hmarr** [comment]
I've just pushed a commit to the repository that should resolve this. Cheers for reporting it.

**Comment by donspaulding** [comment]
Awesome, that was pretty much exactly what I was doing for MyDecimalField ;-)

P.S. Sorry for the ugly formatting.

**Comment by donspaulding** [comment]
Fixed in 90200dbe9ce2d6ced0fa5fb0b3b5cd274015a616
