### ISSUE TITLE
FileField and custom collection

### ISSUE THREAD

**Issue by tkloc** [hmarr/mongoengine#375]
I cannot find a way to store some files in different collection than 'fs'. I need to do something like:

```
class SomeDocument(Document):
  private_file = FileField(collection='private_files')
  public_file = FileField(collection='public_files')
```

and then configure i.e. nginx with gridfs extension just to server files from public_files collection.

when i generate thumbnails, i use:

```
  from gridfs import GridFS
  ...
  fs = GridFS(db, collection=collection)
```

is it possible with mongoengine? am i overlook something?

**Comment by rozza** [comment]
Hi this has recently been added to dev along with mutlidb see: 
https://github.com/hmarr/mongoengine/blob/dev/mongoengine/fields.py#L886

This should work:

``` python

class SomeDocument(Document):
  private_file = FileField(collection_name='private_files')
  public_file = FileField(collection_name='public_files')
```
