### ISSUE TITLE
Dynamic field not checking for parts List length

### ISSUE THREAD

**Issue by Amorano** [hmarr/mongoengine#377]
mongoengine\base.py 

line 983:
           if self._dynamic and parts[0] in self._dynamic_fields:

changed to:

```
        if self._dynamic and len(parts) and parts[0] in self._dynamic_fields:
```

Looks like the assumption is made that parts will always have an element.

I have found that is not always the case.

Checking for length first has seemed to patch this.

**Comment by rozza** [comment]
@Amorano thanks for the report - this is now fixed in dev
