### ISSUE TITLE
Change in EmbeddedDocument unpacking.

### ISSUE THREAD

**Issue by amcgregor** [hmarr/mongoengine#383]
Given the following EmbeddedDocument schema:

``` python
import mongoengine as db

class Participant(db.EmbeddedDocument):
    id = db.StringField()
    name = db.StringField()
```

I accidentally (and successfully) tuple unpacked it:

``` python
participant = Participant(…)
i.origin, i.target = participant
# should have been: i.origin = i.target = participant
```

In this example, origin now equals `"id"` and target equals `"name"`.  For normal unpacking, unpacking the data would be far more useful than unpacking the names of the variables.

**Comment by rozza** [comment]
This is a wont fix - afaict unpacking assignment iterates over iter(Participant.**dict**) so theres no way override that.

**Comment by amcgregor** [comment]
@rozza — This doesn't iterate `Particpant.__dict__`, it iterates `Participant`, thus is controllable using the `__iter__` method on `Participant`.  It's actually fairly trivial to implement, so please re-open.

``` python
class Foo(object):
    def __iter__(self):
        return iter([1,2,3])

a, b, c = Foo()
print a, b, c # 1 2 3
```

**Comment by rozza** [comment]
Ah my bad.

**Comment by amcgregor** [comment]
Moved to: https://github.com/MongoEngine/mongoengine/issues/169
