### ISSUE TITLE
update() semantics confusing

### ISSUE THREAD

**Issue by thomasst** [hmarr/mongoengine#387]
When specifying keyword args in update(), mongoengine should assume by default that we'd like to set those properties. Considering the following statement:

models.Entry.objects.filter(pk=my_doc).update_one(name='Hello')

After executing that line, the document with pk=my_doc will be removed from Mongo (re-running the filter statement will result in an empty queryset). This is very unintuitive, therefore I propose to have mongoengine automatically transform it into a "set" comand behind the scenes:

models.Entry.objects.filter(pk=my_doc).update_one(set__name='Hello')

Also, running update() on a similar queryset returns a "'OperationError: Update failed (multi update only works with $ operators)'", which is similarly confusing.

**Comment by rozza** [comment]
I've added an InvalidQueryError to warn you about doing an update without an op.

**Comment by Alquimista** [comment]
Sorry for coment in this closed issue, I Can'tuse something like it

``` python
kwargs = {name="name", pass="test")
user = User.objects(username=byusername)
user.update_one(**kwargs)
```

why not

``` python
user.update_one(operator="set", **kwargs)
```

**Comment by rozza** [comment]
Probably one for the mailing list - but the main reason is historic in that we try to ape / follow the semantics of mongodb and django
