### ISSUE TITLE
problem with limiting queryset in DTL

### ISSUE THREAD

**Issue by tkloc** [hmarr/mongoengine#398]
Hello,

Sorry for lack of testcase, but i really don't know how to write test for this case.

I have a simple model

``` python
class MTest(Document):
    name = StringField()
    meta = {'collection': 'mtest'}
```

with some data:

``` python
In [2]: for i in range(20):
   ...:     m = MTest(name=str(i))
   ...:     m.save()
```

and next do some pagination:

``` python
In [4]: from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
In [5]: paginator = Paginator(MTest.objects.all(), 2)
```

when I get page and print number of objects (page.objects_list.count())  in django view - values are correct (2), but in template i see very strange behaviour:
page number | number of results
1 | 2
2 | 4
3 | 6
4 | 8
5 | 10
6 | 10
7 | 8
8 | 6
9 | 4
10 | 2

I've described some details in mailing list, but my hack (print self / self.**repr**() ) doesn't work as i expected, because it mess up some other things.

**Comment by tkloc** [comment]
i use latest dev branch. in other project with mongoengine 0.4 everything works fine

**Comment by tkloc** [comment]
one more thing..

when i print paginated queryset in DTL, ie: {{ mtypes }} i see 2 results, but when i iterate over it or call count() i see 4 results (on page 2)

**Comment by tkloc** [comment]
OK, i finally get this working.

problem was in the _cursor function (queryset.py) and it looks like a bug.

when django paginates queryset it calls something like:
queryset[5:20], which means 'skip first 5 rows and fetch 15'

but  _cursor method ...

``` python
            if self._limit is not None:
                self._cursor_obj.limit(self._limit)

            if self._skip is not None:
                self._cursor_obj.skip(self._skip)
```

... is telling pymongo 'skip 5 and fetch 20' !

i've changed this to:

``` python
            if self._limit is not None:
                if self._skip is not None:
                    self._cursor_obj.limit(self._limit-self._skip)
                else:
                    self._cursor_obj.limit(self._limit)

            if self._skip is not None:
                self._cursor_obj.skip(self._skip)
```

and it seems to work fine

**Comment by tkloc** [comment]
and one last comment :)

it was working fine in view, because QuerySet.__ getitem __ has line

``` python
                        self._skip, self._limit = key.start, key.stop - start
```

**Comment by rozza** [comment]
Any chance for a pull request for this?

**Comment by tkloc** [comment]
i've never used git before, so it might be difficult to me;)

**Comment by rozza** [comment]
No worries - I'll review when back in the uk

On Thu, Jan 12, 2012 at 2:08 PM, tkloc <
reply@reply.github.com
