### ISSUE TITLE
Possible threading issues with dereference.py

### ISSUE THREAD

**Issue by djziegler** [hmarr/mongoengine#399]
While trying to add a simple dereference cache to dereference.py I noticed that there is a single global instance of DeReference (used for all dereferencing on all threads), and that the dereference methods store intermediate state on the self of this single global instance.

For example:

self.referenceMap is assigned in **call**() then referenced in _fetch_objects()

So while I haven't had any stompage issues yet, unless I am missing something, this is not thread safe.

I have really enjoyed mongoengine

-David

**Comment by rozza** [comment]
David thanks for reporting - fixing was easy as caching can be done on an instance level rather than a module level..
