### ISSUE TITLE
Add 'update' method to QuerySet to enable atomic updates

### ISSUE THREAD

**Issue by hmarr** [hmarr/mongoengine#4]
Just in the same way that `QuerySet` has a `delete` method to delete all items matching the current query, there should be an `update` method that takes arguments that are in a similar style to query arguments, specifying the field and the operation as the key, and the value as the value e.g.

```
Story.objects(tags='mongo').update(push__tags='database')
Story.objects(slug=story_slug).update(inc__view_count=1)
```

One issue is that the `pymongo.Collection.update` method only received the `multi` parameter, which allows multiple documents to be updated at once, in version 1.1.1. Two options are to either drop support for PyMongo 1.1.1 or to reimplement `update` with `multi` as a Javascript function and use `exec`.

**Comment by mattdennewitz** [comment]
the lazy programmer in me wants to argue that since mongodb is still a fairly new technology, keeping up with newer api features is acceptable.
