### ISSUE TITLE
Top level ReferenceFields forced earlier than intended?

### ISSUE THREAD

**Issue by djziegler** [hmarr/mongoengine#400]
In BaseDocument.**init**, the "Assign default values to instance" loop also has the (possibly unintended) effect of forcing all top level reference fields (without batching).  I discovered this while testing my simple caching reference field, and thought you might like to know.  (this is not actually causing me problems - almost all of the extra dereferences are hitting my cache anyway).

Regards

David

**Comment by rozza** [comment]
Will look into this - do you have a test case handy?

**Comment by djziegler** [comment]
So: I just created a simple test case (instead of the more complicated one involving my own caching code) - and it turns out that I was mistaken - Mongoengine is in fact behaving correctly.

Sorry for the spurious bug report.

**Comment by rozza** [comment]
No problems - I'm always happy for bug reports
