### ISSUE TITLE
__init__() keywords must be strings

### ISSUE THREAD

**Issue by greut** [hmarr/mongoengine#41]
Since the last update, it cannot build the MongoSession again because the keys() are unicode strings.

```
diff --git a/mongoengine/base.py b/mongoengine/base.py
index 83faa92..2dde93b 100644
--- a/mongoengine/base.py
+++ b/mongoengine/base.py
@@ -421,7 +421,7 @@ class BaseDocument(object):
         # class if unavailable
         class_name = son.get(u'_cls', cls._class_name)

-        data = dict((unicode(key), value) for key, value in son.items())
+        data = dict((str(key), value) for key, value in son.items())

         if '_types' in data:
             del data['_types']
```

http://github.com/hmarr/mongoengine/commit/48facec5246dcd9c0b3e543eab2de55e25ce4132

The tests are failing btw.

**Comment by flosch** [comment]
Dunno whether this is really an error or the tests just have to be modified. I'll have a look.

Update: all tests passed here (mongoengine master, python 2.6.5 @ Mac OS X Snow Leopard)

**Comment by flosch** [comment]
We just discovered that kwargs in unicode are allowed since python 2.6.5, 2.6.4 or less raises an error. How should we deal with that? Revert unicode to str?

**Comment by greut** [comment]
This is a python 2.6.5 and above feature that won't work in older versions, sadly.
- Issue #4978: Passing keyword arguments as unicode strings is now allowed.
  http://www.python.org/download/releases/2.6.5/NEWS.txt

**Comment by flosch** [comment]
I reverted it in my fork for compatibility reasons. Sorry for any inconvenience.

**Comment by Amorano** [comment]
Just as a side note, this prevents any version of Maya and Nuke (currently both in 2.6.4) from using ME. Have a lot of code that we had to freeze the version of ME to use.

**Comment by Amorano** [comment]
This issue still pops up for me in version of python under 2.6.5 with the 0.7rc1.

Just pointing it out again as the release notes say ME is supported for python 2.5-->3 but that is not really true if you are using unicode keywords in 2.6.4 or below.

Using Maya 2012x64 with embedded interpreter 2.6.4 (r264:75706, Apr 14 2010, 12:23:05) [MSC v.1500 64 bit (AMD64)]

17:17:00  ERROR   nas.maya                                 Traceback (most recent call last):
17:17:00  ERROR   nas.maya                                   File "d:/dropbox/nas/naspy/nas/maya/**init**.py", line 55, in projectSet
17:17:00  ERROR   nas.maya                                     _production = nas.env().db.Production.objects(prefix=prefix).first()
17:17:00  ERROR   nas.maya                                   File "d:/dropbox/nas/naspy/auxiliary/__all/MongoEngine-0.7rc1/mongoengine/queryset.py", line 878, in first
17:17:00  ERROR   nas.maya                                     result = self[0]
17:17:00  ERROR   nas.maya                                   File "d:/dropbox/nas/naspy/auxiliary/__all/MongoEngine-0.7rc1/mongoengine/queryset.py", line 1178, in __getitem__
17:17:00  ERROR   nas.maya                                     return self._document._from_son(self._cursor[key])
17:17:00  ERROR   nas.maya                                   File "d:/dropbox/nas/naspy/auxiliary/__all/MongoEngine-0.7rc1/mongoengine/base.py", line 1078, in _from_son
17:17:00  ERROR   nas.maya                                     else field.to_python(value))
17:17:00  ERROR   nas.maya                                   File "d:/dropbox/nas/naspy/auxiliary/__all/MongoEngine-0.7rc1/mongoengine/base.py", line 342, in to_python
17:17:00  ERROR   nas.maya                                     for key, item in value.items()])
17:17:00  ERROR   nas.maya                                   File "d:/dropbox/nas/naspy/auxiliary/__all/MongoEngine-0.7rc1/mongoengine/fields.py", line 447, in to_python
17:17:00  ERROR   nas.maya                                     return self.document_type._from_son(value)
17:17:00  ERROR   nas.maya                                   File "d:/dropbox/nas/naspy/auxiliary/__all/MongoEngine-0.7rc1/mongoengine/base.py", line 1097, in _from_son
17:17:00  ERROR   nas.maya                                     obj = cls(**data)
17:17:00  ERROR   nas.maya                                 TypeError: __init__() keywords must be strings

**Comment by Amorano** [comment]
Suggestion:

python_support add a new global (if you have a better way to map a seq to a number =p)

UNICODE = int(''.join([str(x) for x in sys.version_info[:3]])) > 264

then in base:

14: from mongoengine.python_support import (PY3, PY25, UNICODE, txt_type,

1055:         if not UNICODE

Maybe one of these days I will actually fork and submit pull requests =p

Cheers
