### ISSUE TITLE
override primary key?

### ISSUE THREAD

**Issue by pyfun** [hmarr/mongoengine#42]
Hi, I have the following schema, and it failed when loading, it that intentional?

raise ValueError('Cannot override primary key field')
ValueError: Cannot override primary key field

code:
class price1(Document):
  pid = StringField(maxlength=20)

class price2(price1):
  pass

**Comment by hmarr** [comment]
I can't reproduce the error, what causes it? 

To specify that a field should be a primary key, use the `primary_key=True` keyword argument to a field's constructor. You shouldn't create a field named `id` that is not the primary key, as `id` is always aliased to the primary key, or overwritten with a unique primary key field if a specified one is not present.

Also, in the future, would you mind posting this kind of question in the [users mailing list](http://groups.google.com/group/mongoengine-users)?

Cheers,
Harry
