### ISSUE TITLE
Feature request: pre_save for EmbeddedDocument fields

### ISSUE THREAD

**Issue by danaki** [hmarr/mongoengine#426]
I have the following base model:

```
class TimeStamped:
    created = DateTimeField()
    modified = DateTimeField()
    @classmethod
    def pre_save(cls, sender, document, **kwargs):
        now = datetime.datetime.now()
        document.modified = now
        if document.id is None:
            document.created = now
```

However it doesn't work for

```
class Channel(EmbeddedDocument, TimeStamped):
```

Is it possible to implement pre_save for EmbeddedDocument or somehow achieve the goal?

**Comment by michaelurban** [comment]
Take a look at my fork:  https://github.com/mcu/mongoengine

``` python
class TimeStamped(object):
    created = DateTimeField(auto_now_add=True) # Added/Updated upon creation
    modified = DateTimeField(auto_now=True) #  Added/Updated upon creation or save
```

**DISCLAIMER**:  This is my first day w\ MongoEngine, and I only spent about 10 minutes hacking this up.   

It only supports DateTimeFields at the moment, but I plan to keep work on it this weekend...  It's such an obvious feature that I feel like it needs to be addressed before I decide whether to use MongoEngine or not.

I wouldn't mind if someone assigned me to this issue...

**Comment by danaki** [comment]
Mcu, it looks good, but it does the same thing I was trying to achieve with signals. Hence, it doesn't solve my problem. The thing is that EmbededDocument does not have an id, because it doesn't have a separate collection, it's more like substructure put inside in a list for example. Thus, if a Document instance has created/modified is ok when saved, but say if you put an EmbeddedDocument into the list of this Document with append(), the pre_save method of the Document must track this situation and update only these list elements that were triggered. It is clear with "created" for EmbeddedDocument, it's the datetime of element was appended, but what about modified? How to track that I've "touched", e.g. write accessed the embedded element and "modified" must be updated on "parent" Document save?

**Comment by asfaltboy** [comment]
I want to ask @mcu how he extended the DateTimeField with auto_now attribute? I can add the attr to the field but where should I add the value on save/creation? Do you do it on save/validate of Document class? Unfortunately I cannot access your fork :(
