### ISSUE TITLE
bulk save?

### ISSUE THREAD

**Issue by pyfun** [hmarr/mongoengine#43]
Hi, can I create a list of Documents and do a bulk save? or I have to save one by one.

**Comment by mattdennewitz** [comment]
right now, you'll need to do it one by one. its possible to add bulk saves, though.

**Comment by flosch** [comment]
What do you think how should bulk saves look like in mongoengine? How should they work?

**Comment by gregtap** [comment]
In the meantime:

batch_insert_logs = []
log = MyLog(...)
batch_insert_logs.append(log.to_mongo())
db = _get_db()
db.yourcollection.insert(batch_insert_logs)

**Comment by colinhowe** [comment]
I'm interested in this one too. I imagine it might look like:

```
Comment.objects.create_many(list_of_dicts)
```

**Comment by rozza** [comment]
Added a .insert() method to the queryset in feature/insert for review.

Example usage:

``` python
blog1 = Blog(title="code", posts=[post1, post2])
blog2 = Blog(title="mongodb", posts=[post2, post1])

blog1, blog2 = Blog.objects.insert([blog1, blog2])
```

**Comment by rozza** [comment]
This is now in dev.

Example usage:

``` python
blog1 = Blog(title="code", posts=[post1, post2])
blog2 = Blog(title="mongodb", posts=[post2, post1])

blog1, blog2 = Blog.objects.insert([blog1, blog2])
```
