### ISSUE TITLE
Bug with boolean fields that have default of False

### ISSUE THREAD

**Issue by cielecki** [hmarr/mongoengine#440]
Try following code:

from mongoengine import *

connect('testproject')

class Foo(Document):
    bool_field_with_default_false = BooleanField(default=False)

Foo.objects.delete()

f = Foo()
f.save()
print len(Foo.objects.filter(bool_field_with_default_false=False))  # prints 1

f.save()
print len(Foo.objects.filter(bool_field_with_default_false=False))  # prints 0

It seems that the second save should not have this effect. From my investigation the bug is in this line: 

https://github.com/hmarr/mongoengine/blob/master/mongoengine/base.py#L796

The test should say:

if value != None

But this needs verification as the code suggests that some values should be unset if set to default value. Is that the case? it seems risky when you want to search by the default value as in the example above.

**Comment by rozza** [comment]
Hi this has been fixed in dev a while back.
