### ISSUE TITLE
Maximum recursion depth exceeded with 0.5.2

### ISSUE THREAD

**Issue by mahmoudhossam** [hmarr/mongoengine#441]
I have a `Post` class that looks like this:

``` python

class Post(Document):
    title = StringField(required=True)
    content = StringField(required=True)
    date = DateTimeField(required=True)
    slug = StringField(required=True)

```

I can save objects to the database just fine, but when I try to get a specific post, it gives me a `RuntimeError`.

This is the code I'm using:

``` python
def get_post(year, month, day, slug):
     date = date(year, month, day)
     posts = Post.objects(date=date)
     for i in posts:
         if i.slug == slug:
             return i
```

**Comment by rozza** [comment]
I'm not sure what you are trying to achieve here?  Can you make a test case so I can reproduce?

Also why aren't you filtering by slug and date?

**Comment by mahmoudhossam** [comment]
I tried doing this

``` python
def get_post(year, month, day, slug):
     date = date(year, month, day)
     posts = Post.objects(date=date, slug=slug)
     return post.first()
```

But it also yields the same error.

I don't know how to write test cases, but I have my code [here](https://github.com/mahmoudhossam/blog/tree/github/webapp), the relevant modules are `util` and `models`

**Comment by rozza** [comment]
Is this fixed in 0.5.3?

On Wed, Feb 29, 2012 at 10:02 PM, Mahmoud Hossam <
reply@reply.github.com

**Comment by mahmoudhossam** [comment]
There's no 0.5.3 tag, should I clone the repo?

**Comment by rozza** [comment]
Sorry my bad - that was the dev branch.

Can you provide a test case - reproducing the error.   I cant see anything in get_post that would cause a recursion error or your schema.   Please provide a test case reproducing it, at its simplest level.

**Comment by mahmoudhossam** [comment]
The problem was with another part of the code, really sorry about that, closing.
