### ISSUE TITLE
Index on list of references

### ISSUE THREAD

**Issue by danaki** [hmarr/mongoengine#463]
I have a model Book with the field like this:

```
authors = ListField(ReferenceField(Author, reverse_delete_rule=CASCADE, required=True), required=True)
```

Is it possible in mongoengine to describe index in meta['indexes'], currently I get this exception:

  File "/lib/python2.7/site-packages/mongoengine/base.py", line 709, in **new**
    for spec in indicies] + base_indexes
  File "/lib/python2.7/site-packages/mongoengine/queryset.py", line 422, in _build_index_spec
    parts = [field.db_field for field in fields]
AttributeError: 'str' object has no attribute 'db_field'

when I specify indices in Book:

```
    'indexes': [
        'authors.$id'
    ]
```

however this raw query is possible:

db.book.ensureIndex({'authors.$id': 1})

**Comment by rozza** [comment]
I think the best approach here would be to turn off auto creation of indexes using: `auto_create_index` or manually add the index.
