### ISSUE TITLE
FileField Race Condition

### ISSUE THREAD

**Issue by jaredye** [hmarr/mongoengine#465]
fields.py line 916  in 0.6.2 in FieldField

```
def __get__(self, instance, owner):
    if instance is None:
        return self

    # Check if a file already exists for this model
    grid_file = instance._data.get(self.name)
    self.grid_file = grid_file
    if isinstance(self.grid_file, self.proxy_class):
        if not self.grid_file.key:
            self.grid_file.key = self.name
            self.grid_file.instance = instance
        return self.grid_file
    return self.proxy_class(key=self.name, instance=instance,
                            db_alias=self.db_alias,
                            collection_name=self.collection_name)
```

Why does the code store the grid_file into self? It seem to introduce nasty race condition. 

I have found files in fs.files that has no reference from any filefield. I suspect this is the reason.

**Comment by deignacio** [comment]
I found that documents with file fields required an overridden delete to loop through and also delete the files.  

https://github.com/hmarr/mongoengine/pull/492

Is a pull request that looks for fields with proxies and calls delete() on those as well.

Or are you thinking that self.grid_file should only be set if it is actually being returned?  Or perhaps that it shouldn't be stored at all?  Or perhaps if self.grid_file is already defined, can we save some of the other queries

**Comment by rozza** [comment]
Can't see a reason, nowhere references it and tests pass without it being assigned to self.
