### ISSUE TITLE
Session backend is broken in django 1.4

### ISSUE THREAD

**Issue by ghost** [hmarr/mongoengine#469]
The stable release 1.4 from django broke the session backend from mongodb. 

mongoengine/django/auth.py:
class SessionStore(SessionBase):
    def create(self):
        while True:
            self.session_key = self._get_new_session_key()
            ....

This will throw an attribute error when accessed. Following change is needed to make it work again:
            self._session_key = self._get_new_session_key()

**Comment by ghost** [comment]
Duplicate, sorry about that.

**Comment by jachinpy** [comment]
I have the same problem. And just from the merger of remote update down over the code, I cleaned up the browser's cookie, or can's set attribute. in the source code to test shows, the fundamental can't arrive home.

**Comment by jachinpy** [comment]
I have a answer. I have a python virtualenv.  beacause the virtualenv project is wrong.  if don't python's verison no problem, so you can mkvirtualenv new project.  eg:  $mkvirtualenv dev  #then pip install packages   $  rmvirtualenv olderbranch  # delete older project env. try it.
