### ISSUE TITLE
Allow inheritance for Django User document

### ISSUE THREAD

**Issue by mitar** [hmarr/mongoengine#476]
If I want to extend provided Django User document I am getting a warning:

```
... uses inheritance, the default for allow_inheritance is changing to off by default.  Please add it to the document meta.
```

Can `allow_inheritance` be added to Django User document so that it can be extended without a warning?

**Comment by rozza** [comment]
This is in master

**Comment by mitar** [comment]
Great!

**Comment by BBFPHIL** [comment]
Hey. How do you actually change it to allow_inheritance default on?
