### ISSUE TITLE
Extend BaseDocument with post-default fields assignment flag

### ISSUE THREAD

**Issue by marcinkuzminski** [hmarr/mongoengine#480]
Would it be possible to extend the BaseDocument with a flag (similar to _initialised) that would be set after the
`# Assign default values to instance` code. I'm working on some model field validators on the level of setting actual attributes. This works well when used after class instance is created but doesn't when used with creating new instance with arguments from constructor.  Does that makes any sense, and would be possible to add this to mongo ?

**Comment by rozza** [comment]
I could put a hook in there, but validation is often better places in the field classes themselves.  Please continue this on the http://groups.google.com/group/mongoengine-dev
