### ISSUE TITLE
Add support for compressed field names (aka aliasing)

### ISSUE THREAD

**Issue by christarnowski** [hmarr/mongoengine#483]
It is generally considered a good practice to use very short field names in MongoDB documents to preserve disk space and bandwidth (see [A year with MongoDB](http://blog.engineering.kiip.me/post/20988881092/a-year-with-mongodb)). There is currently no such mechanism in MongoDB itself, however MongoEngine could support this technique at model definition level:

``` python
class Profile(Document):
    name = StringField(alias='n')
    birthday = DateTimeField(alias='b')
```

Old models, defined without field aliases, would be automatically converted (both ways) when their `save()` method is called.

**Comment by rozza** [comment]
See: http://tech.yipit.com/2012/02/09/how-to-prevent-memory-bloat-in-mongo/

**Comment by rozza** [comment]
Thats an FYI / reminder for me :D

**Comment by christarnowski** [comment]
@rozza Thanks for the link!

One issue I see with Ben's solution is that the automation is too transparent - you can't simply open your `models.py` file and quickly grasp the actual structure of stored documents. You're basically obfuscating your own database, so debugging of any db-related issues would be a pain; not to mention migrations, versioning etc.

**Comment by rozza** [comment]
Doh! I forgot `db_field` already does this!

http://readthedocs.org/docs/mongoengine-odm/en/latest/guide/defining-documents.html?highlight=db_field#field-arguments

**Comment by christarnowski** [comment]
I have no idea how I missed that. Thanks!
