### ISSUE TITLE
Filtering for property names that contain spaces returns no results

### ISSUE THREAD

**Issue by langri-sha** [hmarr/mongoengine#489]
I have a `Document` that contains a list field of `DynamicaEmbeddedDocument` instances. The dynamic fields I store on those documents have names that I get from elsewhere and they often contain spaces.

I've read that MongoDB key names can [contain any UTF-8 character](https://jira.mongodb.org/browse/SERVER-3229), so as you'd expected mongoengine can store and retrieve documents with field names that contain spaces, but I'm not having any luck using them for querying. Doing something like `Doc.objects.filter(**{'field with space__eq': 'val'})` would always return an empty result, but no exceptions are raised.

**Comment by rozza** [comment]
Hi, theres no `__eq` operator which is why it would fail - it would evaluate that to be a sub document.

This works:

```
 Doc.objects.filter(**{'field with space': 'val'})
```
