### ISSUE TITLE
Use real field names when querying

### ISSUE THREAD

**Issue by hmarr** [hmarr/mongoengine#5]
At the moment, field names used in queries correspond the name under which the field is stored in the database. The name used should correspond to the class variable name set on the Document, which would then be used to retrieve the field and find the name that the database uses, e.g.

```
class Story(Document):
    # STORY_TITLE is what existing data uses
    title = StringField(name='STORY_TITLE')

# Bad, how things currently are:
story = Story.objects(STORY_TITLE='MongoDB Stuff')[0]

# Good, how things should be:
story = Story.objects(title='MongoDB Stuff')[0]
```

**Comment by iapain** [comment]
IMHO "name" should be changed to "db_column" its too confusing. Also, I dont think that we should be able to access data via db_coulmn anyways. It should be for internal reasons.

**Comment by hmarr** [comment]
Yea maybe `name` could be clearer. I don't think that `db_column` fits either, as they're not really strictly columns. How about `db_field`?

> Also, I dont think that we should be able to access data via db_coulmn anyways. It should be for internal reasons.

Is this not already the case? I've made a conscious effort to use the Python name rather than the internal name where possible. Let me know if you've found somewhere that this doesn't apply.

Cheers

**Comment by iapain** [comment]
`db_field` is cool. If you havn't got a time then I'll try to patch this bug in my fork over this weekend.
