### ISSUE TITLE
Document.objects(tags="python") not equiv to Document.objects(Q(tags="python"))

### ISSUE THREAD

**Issue by ericmoritz** [hmarr/mongoengine#50]
I have a document with a ListField of StringFields called "tags"  when I query it with tags="python" it returns documents whose tags contains "python".  This is like the expression, "python" in ["python", "django", "mongo"]

I assume that Q(tags="python") would behave in the same way, however, it acts as the expression ["python"] == tags, which fails for any documents that's not tagged ["python"]

**Comment by hmarr** [comment]
Cheers for submitting this - should be fixed in master now.
