### ISSUE TITLE
A way for DoesNotExist and MultipleObjectsReturned to subclass Django's exceptions

### ISSUE THREAD

**Issue by mitar** [hmarr/mongoengine#502]
It would be great if there would be a way for DoesNotExist and MultipleObjectsReturned exceptions to subclass Django's exceptions, when MongoEngine is used with Django. In this way a lot of code which handles those Django exceptions could be reused. Currently those exceptions are completely separate.

**Comment by rozza** [comment]
We can't couple mongoengine with Django or your framework of choice.  But I
will put this on the roadmap for once framework support is in.

On Tue, May 15, 2012 at 12:14 PM, Mitar <
reply@reply.github.com

**Comment by mitar** [comment]
Framework support?

**Comment by rozza** [comment]
Yeah, I'm starting to get round to this see:
http://mongoengine.org/roadmap.html

Ross

On Tue, May 15, 2012 at 12:18 PM, Mitar <
reply@reply.github.com

**Comment by rozza** [comment]
Linked to django-mongoengine - closing here but will look to implement there thanks @mitar
