### ISSUE TITLE
getattr after setattr of None does not return None

### ISSUE THREAD

**Issue by mitar** [hmarr/mongoengine#505]
Calling `setattr` with `None` value does internally store that `None` in `self._data`, but later calls of `getattr` does not return None, but previous version of the field. This is quite unexpected as you would assume that `getattr` after successful `setattr` will return the same value.

In code, see implementation of `__setattr__` in `BaseDocument`:

```
        # Handle None values for required fields
        if value is None and name in getattr(self, '_fields', {}):
            self._data[name] = value
            if hasattr(self, '_changed_fields'):
                self._mark_as_changed(name)
            return
```

So if `value` is `None`, then `self._data` is set, but after that `return` is invoked. So program flow does not get to:

```
super(BaseDocument, self).__setattr__(name, value)
```

So calling later on `getattr` for the same field returns old value.

**Comment by rozza** [comment]
Thanks @mitar for the ticket - will be in 0.6.11 out today
