### ISSUE TITLE
only does not work....

### ISSUE THREAD

**Issue by ghost** [hmarr/mongoengine#508]
For Example.. In Mongodb..

```
> db.test.findOne({}, {'s.FREE':1})
{
    "_id" : ObjectId("4fb7b248c450190a2000006a"),
    "mapField" : {
            "BOXFLUX" : {
                    "a" : "f",
            }
    }
}
```

The 'mapField' field is made of MapField of Mongoengine.
and 'mapField' field has a log of key and data.. but I just retrieved only 'BOXFLUX'..

this query is not working in MongoEngine....
for example..

```
BoxfluxDocument.objects( ~~ querying ~~ ).only('mapField.BOXFLUX')
```

this query shows me all of data in 'mapField' not just a 'BOXFLUX' 

```
 only('mapField.BOXFLUX') or only('mapField__BOXFLUX') does not work.
```

it retrieves all 'mapField' data, including 'BOXFLUX' one.. something like this

```
{u'BOXFLUX': <Sub: Sub object>,
 u'MENTORS': <Sub: Sub object>,
 u'OPEN ADMINS': <Sub: Sub object>,
 u'POLL': <Sub: Sub object>,
 u'QNA': <Sub: Sub object>,
 u'WIKI': <Sub: Sub object>}
```

How can I retrieve only a field of MapField???

**Comment by rozza** [comment]
Will investigate and fix for next release.

**Comment by rozza** [comment]
http://stackoverflow.com/questions/10679458/mongoengine-retriving-only-some-of-a-mapfield/

**Comment by rozza** [comment]
Works for me heres an example test case:

```
def test_only_with_mapfields(self):

    class BlogPost(Document):
        content = StringField()
        author = MapField(field=StringField())

    BlogPost.drop_collection()

    post = BlogPost(content='Had a good coffee today...', author={'name': "Ross", "age": "20"}).save()

    obj = BlogPost.objects.only('author__name',).get()

    self.assertEquals(obj.author['name'], "Ross")
    self.assertEquals(obj.author.get("age", None), None)
```

Can you provide an example of it being broken?

**Comment by ghost** [comment]
As always, Ross Really Thanks a lot!!!!!!!!! 

I found my fault.. that is.. I used 'only' twice..

For example,

```
BlogPost.objects.only('author').only('author__name') 
```

something like this..

I spent a whole day finding out what is wrong with Mongoengine..

so.. my dumb conclusion was...

```
BlogPost.objects()._collection.find_one(~~ filtering query ~~, {'author.'+ name:1})
```

something like this.. 

but as you know it's a just raw data not a mongoengine query..

after this code, I cannot run any mongoengine methods...

Anyway..

**In my case, I should have to query depending on some conditions.**

**so it will be great that 'only' method overwrites 'only' methods written before.. In my humble opinion.**

I hope this feature would be integrated with next version.. 

Right now, I have to code duplicate code.. for example..

not this code...

```
query = BlogPost.objects()
query( query~~).only('author')
if name:
    query = query.only('author__'+name)
```

this code

```
query = BlogPost.objects()
query( query~~).only('author')
if name:
    query = BlogPost.objects().only('author__'+name)
```

so.. I think.. the second one looks dirtier than first one.

of course, the first code shows you all all data 
using "only('author')" not "only('author__name')

Thanks A LOT!!!!!!!!!

Ross, you saved me!!! Thanks.. (I thought Mongoengine could not simply do those queries.)

**Comment by ghost** [comment]
anyway!!! Mongoengine is great!! and AWESOME!!! 
and Rozza really really really really Thanks a lot!!!!
