### ISSUE TITLE
GeoLocationField bug

### ISSUE THREAD

**Issue by stopdesign** [hmarr/mongoengine#52]
GeoLocationField.to_python() method should return something.
I mean, something useful, not just keys of the array.
possible:
    def to_python(self, value):
        return (value['x'], value['y'])

Use a 'dict' type to store the location - a bad idea because 2d-index understand the order of elements, not their keys.

to_mongo method returns
    {'x': value[0], 'y': value[1]},
but in the mongo base I see
    "point" : {
        "y" : 56.30342010046667,
        "x" : 43.97127628326416
    },
because python doesn't save order in dict:
    a = {'x': 10, 'y': 100, 'z': 150}
    print a # {'y': 100, 'x': 10, 'z': 150}

perhaps, to_mongo method should return value without any changes...

**Comment by flosch** [comment]
GeoLocationField is replaced by the new GeoPointField. This should solve your issue. Please close this issue.

**Comment by stopdesign** [comment]
Thanks!
