### ISSUE TITLE
Use a class with Document and EmbeddedDocument together, with a custom primary_key

### ISSUE THREAD

**Issue by Tydus** [hmarr/mongoengine#530]
I found an issue when I tried to use a document for both main and embedded ones. But if I use a custom field for primary key, it refused to save my document.

This issue can be replay with this.

``` python
from mongoengine import *

class foo(Document,EmbeddedDocument):
    bar=StringField(required=True,primary_key=True)

connect('test')

foo(bar='test').save()
assert len(foo.objects)
```

I don't sure if this is a issue.
I also don't sure if multiple inheritance is right for mongoengine, if not, how to workaround it.

**Comment by Tydus** [comment]
And when I remove `primary_key=True', it seems to work well.

**Comment by rozza** [comment]
Ok slightly interesting use case here.  You might have to declare your indexes independently - just add unique is True for the specific documents / locations that you need this functionality for.

**Comment by rozza** [comment]
Sorry closed this prematurely.

This is a **bad** idea™ as primary_key really means the `_id` and utilises the default index.  As EmbeddedDocuments don't require a `_id` primary key semantic is not appropriate here.  You should really separate this out into two different classes and use `required=True, unique=True` for the EmbeddedDocument `bar` value.
