### ISSUE TITLE
$pull test case does not work as designed

### ISSUE THREAD

**Issue by mattdennewitz** [hmarr/mongoengine#54]
http://github.com/hmarr/mongoengine/blob/master/tests/queryset.py#L669

i'm not sure why the assertion that comment #2 is not in the list, but looking at the list itself shows that both comments remain.

**Comment by yashh** [comment]
True, I was able to replicate the same issue. delete embeddedDocument does not work as it should

**Comment by hmarr** [comment]
This was happening because EmbeddedDocuments can't be compared for equality. Changed the test to use a list of strings rather than embedded docs - doesn't look like Mongo supports $pull based on embedded fields.
