### ISSUE TITLE
Dynamic collection name for same Documents

### ISSUE THREAD

**Issue by ghost** [hmarr/mongoengine#541]
Currently, mongoengine accepts callable for collection in meta. Since this is called while preparing class/object in _ _new_ _, it calls the callable only once. Thereafter the collection name is fixed. 
In my usecase, I have logs which i need to insert in collections for the month when log was generated (with the help of timestamp, a collection name is generated like log_0612 for June/2012. 
This cannot be achieved ideally in mongoengine at the moment. Though, I can do it by changing the value  ModelClass._meta['document'] = 'mycollection_name". But this affects all objects of this document model.

**Comment by rozza** [comment]
Hi,

This sounds similar to what sharding is used for - to split a collection, but doing this in the app could be problematic.  The issue here is that ModelClass.objects.all() has to have a collection to be able to query the data..

Perhaps defining how you would like to use mongoengine with some pseudo code would help think of a solution for this issue.

**Comment by ghost** [comment]
Hi,

Yes, sharding is sort of solution, but if I want to archive data based on mo/yr, so I can process it with batch, or copy directly to other DB instance.
I would like to do it as:

```
# Get a model class and configure it to use another collection
ModelClass().save() will insert data into default collection as defined in meta. 
```

But if I do -
modelclass = ModelClass.get_manager(collection_name=None) # Optional
modelclass(attr=Value).save() 
modelclass.objects.all()
OR
modelclass.all()

If the optional parameter collection_name is None, it will return manager which is set with default collection as set in meta. If the collection name is callable, it will be called to get the collection name.

This may not be a good solution, I am think of some more way to achieve it. But my main concern is, MongoDB does not  put any restrictions on which doc can be stored in which coll. It opens a lot of way to do things with mongodb where my usecase is just one small part.  But once I use mongoengine, the opportunity to do wide variety of usecase is narrowed and I am limited to store one type of doc in predefined collection.

**Comment by ghost** [comment]
Oh I am sorry, the Markdown just made  line "Get a model class and configure it to use another collection" look like I am shouting here. Please ignore it. I don't see anyway to edit my comment.

**Comment by vladzloteanu** [comment]
+1

**Comment by rozza** [comment]
Will add a context manager similar to switch db: 
Please follow: MongoEngine/mongoengine#220

**Comment by rozza** [comment]
Added a switch_collection context manager in 0.8 branch
