### ISSUE TITLE
DynamicDocument doesn't utilize descriptors

### ISSUE THREAD

**Issue by maxcountryman** [hmarr/mongoengine#543]
Specifically, it seems like the DynamicDocument document class should handle property decorators. However, in practice this doesn't seem to work. Ideally, I'd like to be able to decorate a method as a property and then use that property in a queryset.

**Comment by maxcountryman** [comment]
Okay I think I misunderstood the thrust of DyanmicDocument...and perhaps I've come up with a partial solution to my problem. I'm wondering if creating a custom `document_property` decorator could trick the Document class into seeing the dynamic attribute/field? Something like this:

``` python

class document_property(object):
    def __init__(self, fget=None, doc=None):
        self.fget = fget
        self.__doc__ = doc

    def __get__(self, obj, objtype=None):
        if obj is None:
            return self
        if self.fget is None:
            raise AttributeError('attribute unreadable')
        obj.__setattr__(self.fget.func_name, self.fget(obj))
        return self.fget(obj)
```

**Comment by rozza** [comment]
Can you post some pseudo code of how you want to use the decorators?

**Comment by maxcountryman** [comment]
Well, there's the above comment with a snippet. Basically I think it would be nice if this worked:

``` python
class Model(Document):
    @property
    def foo(self):
        return 'bar'

m = Model(); m.save()

Model.objects(foo='bar')  # should return something
```

However this doesn't actually work. My custom `document_property` causes MongoEngine to see the property as an attribute of the model class by calling `__setattr__`. Does this potentially break things?

**Comment by maxcountryman** [comment]
Sorry, ignore my `document_property` class, it doesn't actually do what I want. I must have tested against the wrong data. I would really love to find a way to use properties with my models as I described above however...I have quite a few fields that need to be constructed dynamically and in some cases I need to be able to query by them. So I really appreciate any thoughts or advice you might have.

**Comment by rozza** [comment]
You can use properties - but that data wont be stored in the database and therefore cant be queried against.  It seems like you need to use an actual field.

**Comment by maxcountryman** [comment]
So my question is: is there a way to write a custom property decorator that would behave as a field?

**Comment by rozza** [comment]
For use when querying?  You can't ..

On Wed, Jul 25, 2012 at 3:17 PM, Max Countryman <
reply@reply.github.com

**Comment by maxcountryman** [comment]
I don't really see why not? Shouldn't this be possible with a DynamicDocument? Isn't the whole point that fields aren't predefined? So by extension, shouldn't I be able to wrap field creation in a property decorator? (Actually, imo this should just work out of the box with DynamicDocument since property is a descriptor and DynamicDocument should use descriptor methods to set fields.)

**Comment by rozza** [comment]
OK - lets make sure we are on the same page here and not talking cross
purposes.

You want to be able to query against property?  If its static you will
return all documents - as they would all match.  If its dynamic you'd have
to return all documents and then filter on the application side.

I think I must be missing something here.

Ross

On Wed, Jul 25, 2012 at 3:34 PM, Max Countryman <
reply@reply.github.com

**Comment by maxcountryman** [comment]
Why would a dynamic value return all documents? That's making a big assumption that all dynamic values are the same. What if, for example, I have a dynamic value dependent on some attribute of a document that will vary between documents? I have such a case now. This means that the property would return different results for different documents. Obviously using vanilla property doesn't work for querying. But in my above example you can force mongoengine to see the attribute as a query-able field if you call **setattr** in the scope of fget. This only works if you actually **get** that attribute first but after that you can query by it. So it's not impossible but why isn't DynamicDocument written in such a way to account for descriptors such as property?

**Comment by rozza** [comment]
No still not seeing the use case of using a property syntax here - properties on all Documents don't cause data to be stored in the database.  

DynamicDocuments allow you to add any data into the database - you just don't have to define a field for that data and you can query against it.

**Comment by maxcountryman** [comment]
I'm not sure what's not to see? I have a document with an attribute, let's call it foo. Foo has some value a, 1 to 10. I have another document called bar. Bar has a list of foo references. Bar would like to set an aggregate value b of all of foo.a. Bar should be able to query by this composite value b. Foo may change value a so simply setting b on bar on save is not sufficient. What we need is a property and we need to be able to query by it. Make sense?

**Comment by rozza** [comment]
No - dont use a property use a field and then manage the data that you set
/ store in the database.

Properties dont store data in the database.

**Comment by maxcountryman** [comment]
No, I can't do that. The data is dynamic. Where am I not being clear about the use case?

**Comment by rozza** [comment]
I should also mention to implement a property that is actually a field, would break _everyones_ code.  

If you have a field that has dynamic types of data and you want that - you can use the `DynamicField` when declaring the field which `DynamicDocument` utilise in the background.

**Comment by rozza** [comment]
Well if its dynamic - just dont add a property with the same name as the field you wish to use.

**Comment by maxcountryman** [comment]
Huh? How would that break everyone's code? That doesn't make any sense... I wrote such a custom decorator and no ones code was broken.

**Comment by rozza** [comment]
https://github.com/MongoEngine/mongoengine/blob/master/tests/test_dynamic_document.py - gives examples of how to use dynamic documents.  Dynamic fields are set / queried against no need for a properties.

**Comment by maxcountryman** [comment]
I think you're getting confused by the terms here: the data that needs to be set is dynamic. It's the result of iterating over a list of objects. The objects may change over time and the resultant value should reflect this. This is exactly what a property descriptor does best.

**Comment by maxcountryman** [comment]
Also don't get confused by the fact that we're referring to @property throughout because actually it would need to be implemented as a custom decorator, e.g. `document_property`, to account for the fact that DynamicDocument will only see attributes as fields that are set via `__set__`. However this can be done in the scope of the fget method of a custom property descriptor.

**Comment by maxcountryman** [comment]
Here's a simple example, just to clarify:

``` python
class Foo(Document):
    a = IntField()


class Bar(DynamicDocument):
    foos = ListField(ReferenceField('Foo'))

    @custom_property
    def a(self):
        value = 0
        for foo in foos:
           value += foo.a
        return value


# set some foos
foo1 = Foo(a=5)
foo2 = Foo(a=2)
foo1.save(), foo2.save()

# set a bar
bar = Bar(foos=[foo1, foo2])
bar.save()

assert bar.a == 7
assert Bar.objects(a=7).first() is not None
```

**Comment by rozza** [comment]
OK, there are going to be issues with this approach and you will have to
ensure you call a() to generate and set and store new values in the dynamic
data attribute, so they are stored into the db.

Traditionally, people have used signals to generate this data before saving
/ updating.  You have to be careful with with atomic updates so not to miss
the regeneration of a.
 On Jul 25, 2012 4:57 PM, "Max Countryman" <
reply@reply.github.com>
wrote:

**Comment by maxcountryman** [comment]
Okay. Thank you for your feedback. That's valuable information. I was thinking using a signal would be preferable but it doesn't seem like there's a signal that fires before every query, right?
