### ISSUE TITLE
$in operator on a ListField throws an exception

### ISSUE THREAD

**Issue by alonho** [hmarr/mongoengine#550]
Reproduction:

```
from infra.mongo import configure_mongo
from mongoengine import *

configure_mongo()

class Coll(Document):

    list_field = ListField(IntField())

Coll(list_field=[1,3]).save()
list(Coll.objects(list_field__in=[[1, 3], [1, 2]]))
```

this throws: TypeError: int() argument must be a string or a number, not 'list'

**Comment by rozza** [comment]
Thats correct if you're doing an in query you must provide a flat list.
 Are you wanting to do an or query here or even an exact match?

On Wed, Aug 1, 2012 at 10:55 AM, alonho <
reply@reply.github.com

**Comment by alonho** [comment]
exact match. why flatten the list? comparing lists as items is a valid query.

**Comment by rozza** [comment]
ok - the in statement here is expecting a list of integers as declared by the ListField(IntField)
looks like you need to do an $or here using a Q query:

Coll.objects(Q(list_field=[1, 3]) | Q(list_field=[1, 2]))
