### ISSUE TITLE
Just a question about ListField(ReferenceField())

### ISSUE THREAD

**Issue by PhoenixAndMachine** [hmarr/mongoengine#552]
How many ReferenceFields can a ListField contain ?

**Comment by rozza** [comment]
One for the user group: http://groups.google.com/group/mongoengine-users

A ReferenceField can reference a single type of document and a list field can store as many references as you need (up to the max document size limit 16mb).  But every growing lists are an anti pattern in mongodb and dont scale well - so it might be suboptimal for you.

If you need to store references to different types of documents use GenericReferenceField
