### ISSUE TITLE
UUIDField error

### ISSUE THREAD

**Issue by llonchj** [hmarr/mongoengine#555]
There is a bug in UUIDField that raises InvalidDocumentError on UUIDField.to_python

InvalidDocumentError: Invalid data to create a `TestDocument` instance.

**Comment by rozza** [comment]
Please report issues on: http://github.com/MongoEngine/mongoengine

Fixed in MongoEngine/mongoengine@f99b7a811b3ea8b2930dbc72f2a5bfc1f0116278
0.6.20 coming today.

**Comment by llonchj** [comment]
Thanks, i'll clone MongoEngine/mongoengine.
