### ISSUE TITLE
gridFSProxy  problem  when call grid_file.delete()

### ISSUE THREAD

**Issue by ruandao** [hmarr/mongoengine#566]
when upload a file to a model's field
for e.g. 
   class XXX(document):
           photo = ImageField()
on view:
     ...
    XXX.photo = photo
    ...

the first time , it will be ok, but if you try to do it again, it will raise a 'NoneType' object has no attribute '_fields'
it was case on line 1033
python2.7/site-packages/mongoengine/fields.py in __set__
            # If a file already exists, delete it
            if grid_file:
                try:
                    grid_file.delete()                          ## when run after this line, grid_file will be a None object 
                except:
                    pass
                # Create a new file with the new data
                grid_file.put(value)                           ##this line will raise error##
            else:
                # Create a new proxy object as we don't already have one
                instance._data[key] = self.proxy_class(key=key, instance=instance,
                                                       collection_name=self.collection_name)
                instance._data[key].put(value)
        else:

this is local value on the snippet:
grid_file                <ImageGridFsProxy: None>
instance                   <UserProfile: ruandaop;;;;;;;;;>
self                            <mongoengine.fields.ImageField object at 0xb65cd66c>
value                  <InMemoryUploadedFile: Screenshot from 2012-08-22 02:24:59.png (image/png)>
key                         'photo'

when i run into grid_file.delete()

 def delete(self):
          # Delete file from GridFS, FileField still remains
          self.fs.delete(self.grid_id)
                                                                          # on this line self object was ok
          self.grid_id = None                              # but on this line self object was be None Object
          self.gridout = None
          self._mark_as_changed()
# 

now this problem can be go around by simple call delete() on ImageFile
for e.g. 
   class XXX(document):
           photo = ImageField()
on view:
     ...
     if photo:                                           # look this two line
          XXX.photo.delete()                  #
    XXX.photo = photo
    ...

but I think may be ImageField should be allow to simple overwrite like this: xxx.photo = new_photo

**Comment by rozza** [comment]
Moved to MongoEngine/mongoengine#86

**Comment by rozza** [comment]
Just an FYI - we're moving! Please report issues on: http://github.com/MongoEngine/mongoengine
