### ISSUE TITLE
Tag 0.6.20

### ISSUE THREAD

**Issue by dokkaebi** [hmarr/mongoengine#572]
I was just trying to diff 0.6.20 (which I have installed) against master or against 0.7, but realized I don't have a hash for 0.6.20.

Could you guys tag 0.6.20 for easier comparison? This might be useful for other versions as well, but since 0.6.20 is stable and current I think it is the most important.

**Comment by rozza** [comment]
Hi - tags can be found on https://github.com/MongoEngine/mongoengine

The latest stable is v0.7.5

Ross

**Comment by dokkaebi** [comment]
Nice, thank you.

Austin
