### ISSUE TITLE
EmailField fails on validation for empty strings and does not provide for required = False

### ISSUE THREAD

**Issue by ghost** [hmarr/mongoengine#577]
While failing on empty strings is absolutely correct, it would be nice to have email fields to not fail on validation when they have been declared as required = False.

My proposal would be to extend upon the BaseField._validate method to check for whether the field is required, and test for whether it is either None or empty after a white space strip, and return early if either is the case.

The rationale of this is that it will save you a lot of extra code in your application where you have to (django that is)

if form.cleaned_data['email']:
    document.email = form.cleaned...

TIA!

**Comment by rozza** [comment]
This is fixed in 0.7.9
