### ISSUE TITLE
from .<Module> import * incompatible with 2.5

### ISSUE THREAD

**Issue by Amorano** [hmarr/mongoengine#578]
MongoEngine-0.8.0\mongoengine\base__init__.py
MongoEngine-0.8.0\mongoengine\queryset__init__.py

resetting them to:

from field_list import *
from manager import *
from queryset import *

etc....

repairs the issue.

Are the plans to drop 2.5?  Maybe deprecating with DeprectionWarnings (like in pymongo) would be good first?

**Comment by rozza** [comment]
logged in the https://github.com/MongoEngine/mongoengine
