### ISSUE TITLE
order_by doesn't work with ReferenceField

### ISSUE THREAD

**Issue by flosch** [hmarr/mongoengine#59]
As the title says, order_by() doesn't work with ReferenceFields. I'm aware of that might be an performance issue but maybe it can be realized on server-side.

**Comment by hmarr** [comment]
Not sure about this - as mongo doesn't support it it would be a pretty slow operation. Might be possible with map reduce though...
Edit: you are talking about Doc.objects.order_by('ref.attr'), right?

**Comment by rozza** [comment]
Closing this as its a won't fix and not supported by mongo

**Comment by rozza** [comment]
Potentially a work round could be the denormalized field concept described in #32 but currently thats just an idea.
