### ISSUE TITLE
Django generic views support

### ISSUE THREAD

**Issue by jdx** [hmarr/mongoengine#61]
The django.views.generic.list_detail.object_list generic view does not work. I think if the QuerySet class just implemented _clone() it should work though.

http://dpaste.com/222219/

**Comment by jdx** [comment]
Accidentally closed my other task

**Comment by hmarr** [comment]
The dpaste link has expired - if you want to fork v0.4 and add a fix I'd be happy to include this.
Cheers,
Harry

**Comment by ixc** [comment]
Done, in https://github.com/ixc/mongoengine/commit/4c3297e45044597c8a037e398a883c90e743263d

(I can't see the need to do a proper clone - did I miss something?)

**Comment by ixc** [comment]
Ah yes, cloning is for preserving the qs when it's paginated. Update in https://github.com/ixc/mongoengine/commit/fe8389f33c66a903c8377662bf188c85ef3d3cef

**Comment by ixc** [comment]
And a deep copy version in https://github.com/ixc/mongoengine/commit/104ec7d6dd0f4b2ecb1be5dbab8a129cbe9175fa

**Comment by iapain** [comment]
IMO we need to ask first ourself that we need `_clone`  in mongoengine or is it just required for django and if answer is no then better way would be to subclass queryclass and hook into django generic view.

**Comment by collinanderson** [comment]
Here is my workaround to increase Django compatibility:

```
from django.db.models.query import QuerySet
class DjangoLikeQuerySet(document._meta['queryset_class'], QuerySet):
    def __nonzero__(self):
        return bool(len(self))
    def _clone(self):
        return self
    def using(self, db):
        return self
    @property
    def model(self):
        return self._document
document._meta['queryset_class'] = DjangoLikeQuerySet
```

**Comment by rozza** [comment]
We've added a clone() method to `dev` does hooking a _clone method into that work?

I agree with @iapain about if _clone actually _needs_ to be in mongoengine core and I like @collinanderson implementation, by decoupling and using a custom django query set, also there are more methods for the queryset there..

Thoughts?

**Comment by rozza** [comment]
Closing issue - no action
