### ISSUE TITLE
Average function return NaN

### ISSUE THREAD

**Issue by Ankhbayar** [hmarr/mongoengine#63]
Average function has error. 
http://github.com/hmarr/mongoengine/blob/v0.4/mongoengine/queryset.py#L893 May be this is a error.
 **sum** is good work.

```
from mongoengine import *
# Checkout from Branch v0.4 at 2010/07/28
connect("test_average")

class BlogPost(Document):
    title = StringField(primary_key=True)
    rank = IntField(default = 0)

BlogPost.drop_collection()

post1 = BlogPost(title="Post #1")
post2 = BlogPost(title="Post #2")
post3 = BlogPost(title="Post #3")

post1.save()
post2.save()
post3.save()

BlogPost.objects.average('rank') # 0 but return NaN - ERROR
BlogPost.objects.sum('rank') # 0 it is a OK
```

**Comment by hmarr** [comment]
In the case illustrated, I think NaN is a valid value. However, there was an error in the JS that meant that zeros weren't taken into account (not comparing to undefined), which is now fixed - so thanks for bringing this up!
