### ISSUE TITLE
No manner in which to pass "timeout" or "snapshot" args to find method on instances of pymongo.collection.Collection

### ISSUE THREAD

**Issue by richardhenry** [hmarr/mongoengine#65]
Not being able to specify a timeout (especially!) or use snapshots for certain queries is a little limiting. We're having to fallback to PyMongo from time to time.

Reference:
http://api.mongodb.org/python/1.3%2B/api/pymongo/collection.html#pymongo.collection.Collection.find

**Comment by hmarr** [comment]
Fixed in http://github.com/hmarr/mongoengine/commit/012352cf24e55558c9638ff29ad36010f98e34a6
