### ISSUE TITLE
Needs support for $or operator, added in MongoDB v1.5.3

### ISSUE THREAD

**Issue by richardhenry** [hmarr/mongoengine#66]
Reference:
http://www.mongodb.org/display/DOCS/Advanced+Queries#AdvancedQueries-%24or

**Comment by hmarr** [comment]
I'm working on a reimplementation of Q-objects that uses the $or operator rather than javascript - it's in a branch called 'new-q-objects' at the minute.

**Comment by hmarr** [comment]
I've merged the new Q objects into v0.4 so closing this issue. Let me know if this is sufficient.
Cheers,
Harry
