### ISSUE TITLE
users__email="..." doesn't work with ListField

### ISSUE THREAD

**Issue by xonatius** [hmarr/mongoengine#68]
For example:

<pre>
class User(Document):
    email = StringField()

class UsersIn(Document):
    users = ListField(ReferenceField(User))

In [17]: user1 = User(email="e@ma.il")
In [18]: user1.save()
In [19]: users_in = UsersIn(users=[user1])
In [20]: users_in.save()
In [21]: len(UsersIn.objects())
Out[21]: 1
In [22]: len(UsersIn.objects(users__email="e@ma.il"))
Out[22]: 0
In [23]: len(User.objects(email="e@ma.il"))
Out[23]: 1
</pre>

**Comment by xonatius** [comment]
It also happends for any ReferenceField even without using ListField.

**Comment by hmarr** [comment]
This isn't actually supported by MongoDB. Generally you'd first fetch all the users with the given email first, then query the UsersIn table with the result set. Perhaps at some point we could provide a helper for doing that, stick something on the mailing list if you think it'd be worth doing.
