### ISSUE TITLE
startswith, endswith, contains, etc. are not escaped

### ISSUE THREAD

**Issue by ghost** [hmarr/mongoengine#70]
I'd expect a query like `Collection.objects(f__istartswith="1.2.3")` to result in the mongo query `{ _types: "Collection", accession_no: /^1\.2\.3\./i }`, but the '`.`'s are not escaped, so they match any character in the regex.

Escaping the value with `re.escape()` in `fields.prepare_query_value()` would fix this. However, I'm not sure it's desired behaviour, or whether fixing the documentation for  would be preferred.

If a regex version is needed for a particular query, then it could be supplied explicitly.

**Comment by hmarr** [comment]
This is now fixed in v0.4 - I merged your fork in (so **raw** etc as well). Cheers for the contribution.
Harry
