### ISSUE TITLE
Make it possible to override objects QuerySet

### ISSUE THREAD

**Issue by danjac** [hmarr/mongoengine#72]
At present you cannot override the base QuerySet class. You can use queryset_manager to add additional filters to the QuerySet, but there is no way (as far as I can see) to use a custom QuerySet class instead (in Django, you can override "objects" with your own QuerySet class).

**Comment by hmarr** [comment]
Fixed: http://github.com/hmarr/mongoengine/commit/f11ee1f9cf60979fbb5c6768219225202d510951

**Comment by danjac** [comment]
Great, thanks.
