### ISSUE TITLE
StringField validation should accept u'' when required=False

### ISSUE THREAD

**Issue by jkur** [hmarr/mongoengine#74]
StringField and inherited types don't behave like you would expect from the django view (i think). CharField (StringField for mongoengine) defaults to a TextInput in Django-Forms (also in mongoforms). This input has an _empty value_ of u'' (the empty string). mongoengine raises a ValidationError Exception, which it shouldn't for Types based on StringField, when the particular field is  _required = False_.

Example:
    import mongoengine
    class B(mongoengine.Document):
        url = mongoengine.URLField(required=False)

```
b = B()
b.url = u''
b.validate()
```

results in:
    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
      File "/usr/local/lib/python2.6/dist-packages/mongoengine-0.3-py2.6.egg/mongoengine/base.py", line 337, in validate
       field._validate(value)
       File "/usr/local/lib/python2.6/dist-packages/mongoengine-0.3-py2.6.egg/mongoengine/base.py", line 99, in _validate
       self.validate(value)
       File "/usr/local/lib/python2.6/dist-packages/mongoengine-0.3-py2.6.egg/mongoengine/fields.py", line 92, in validate
        raise ValidationError('Invalid URL: %s' % value)

It should validate if the (String)Field is not required, since in django-forms the TextInput sends an empty string and not None.

**Comment by hmarr** [comment]
What do you think should happen in this case - don't store a value at all if it is an empty string? Arguably, each field should only store a valid value or nothing at all, and the empty string isn't technically a valid url... I'd be interested to hear your thoughts.

Cheers,
Harry

**Comment by jkur** [comment]
Well, i think that it's more a question of definition, if an empty value is valid for a URL or not. But since mongodb is schema-less it would prefer not to store a value at all for the empty string but validate it as true, if the field is not required.

For me the important thing is, that it's consistent with the forms in django-forms. And there the empty value for TextInput (URLField) is the empty string and not None.
http://docs.djangoproject.com/en/1.2/ref/forms/fields/#urlfield
Right now you can't use a django-form URLField and store it's value with the mongoengine wrapper in an URLField, because it will never validate if it's empty, which would be perfectly okay, if the field is not required.

Anyway, that is the way i would expect it. Does that help?

**Comment by hmarr** [comment]
I'm reluctant to always store no value when a blank string is provided as some people would want to make a distinction between nothing and an empty string, however I do appreciate your point and reckon that _something_ should be done about it.

I'm planning on releasing v0.4 today - nothing will make it in for this release so in the mean time I'd suggest one of three options. Firstly, you could just preprocess the data (maybe use clean methods in django forms). Secondly, you could subclass URLField and override the regex. Thirdly, you could take a look at http://github.com/stephrdev/django-mongoforms or http://github.com/sethtrain/django-mongoengine and perhaps fork them to solve the problem if they don't already.

Perhaps an option for the next version would be to add a parameter to StringFields called something like store_on_blank? Let's keep the discussion going.

Thanks,
Harry

**Comment by rozza** [comment]
Closing issue - see similar discussion in refs #197
