### ISSUE TITLE
WTForm integration

### ISSUE THREAD

**Issue by n1k0** [hmarr/mongoengine#75]
Would be nice to have WTForm integration in mongoengine… or the other way around ;) Someone seems to have [started something](http://github.com/pplante/wtforms/tree/master/wtforms/ext/mongoengine/) in his WTForm fork, and it definitely looks promising… 

I think some collaboration would be great on this topic :)

**Comment by n1k0** [comment]
Just to keep the world informed, Dan Jacob just told me on Quora that he was working on a flask-mongoengine extension, with WTForm support targetted https://bitbucket.org/danjac/flask-mongoengine

And this is great news.

**Comment by iapain** [comment]
I don't think we should support any forms within mongoengine. I believe mongoengine is an ORM and should restrict to it's functionality. A nice way to integrate form is already mentioned in your example.

**Comment by rozza** [comment]
Hi,  I'm currently working on a Flask extension that has WTForms support: https://github.com/sbook/flask-mongoengine/

I agree with @iapain - this is outside the remit of the mongoengine core.
