### ISSUE TITLE
Add tree helper methods / classes

### ISSUE THREAD

**Issue by hmarr** [hmarr/mongoengine#8]
Make it nicer to work with trees in MongoEngine.

See:
http://www.mongodb.org/display/DOCS/Trees+in+MongoDB
http://seancribbs.com/tech/2009/09/28/modeling-a-tree-in-a-document-database/

**Comment by sharoonthomas** [comment]
@hmarr Is there any blueprint on this issue ? do you have any ideas in mind. We currently have this requirement on one of our projects and would like to help.

**Comment by hmarr** [comment]
@sharoonthomas nope, not yet. Happy to hear your thoughts on it.

**Comment by sharoonthomas** [comment]
@hmarr I have pushed a commit to my fork of the repository. It implements Ancestor Array as explained in the Mongo documentation link. The missing part is how the ancestry of the descendants of an existing record will be updated. Can you give your suggestion on that ?

https://github.com/sharoonthomas/mongoengine/commit/d9a2a02466fe2cc5c91a834bc694e033b280d5d8
