### ISSUE TITLE
ListField validation issue

### ISSUE THREAD

**Issue by lxsameer** [hmarr/mongoengine#81]
when i try to use a ReferenceField via a ListField i got a item validation error no matter what type of variable i use for that ListField. 

i solve the problem , the problem was the "pass" keyword that you used in the validate method of BaseField ( line 83 ), i change that to return value , and problem was solved.

it is not good to use "except Exception" or "except" in python code you use an except part in your code related to this issue , an that raise a validation error but the real exception hide in your code by using that

**Comment by hmarr** [comment]
I can't replicate this issue - which version are you using? Would you mind posting some code that demonstrates this? (Replication attempt: http://github.com/hmarr/mongoengine/commit/f6661419816157bec89db3f97b4f8d4a95c67897)
