### ISSUE TITLE
.count() not working or missunderstood

### ISSUE THREAD

**Issue by dzida** [hmarr/mongoengine#82]
Hi,

I have in my view:
votes = Vote.objects() #also tried Vote.objects

In my template I can iterate over my votes and this is OK. but when I try to render number of votes in template using: {{votes.count}} it ends with "None" put instead of number of Votes.

Am I doing something wrong or this is some bug?

**Comment by hmarr** [comment]
Thanks for reporting this - it was due to an AttributeError not being raised and has been fixed on the v0.4 branch by http://github.com/hmarr/mongoengine/commit/dcec61e9b2738f9fc3bd0f09a2cb1bc631438c66
Cheers,
Harry
