### ISSUE TITLE
Cannot override _id field with IntField

### ISSUE THREAD

**Issue by radev** [hmarr/mongoengine#83]
That code:

```
from mongoengine import Document as BaseDocument,IntField, StringField

class Document(BaseDocument):
    id = IntField(primary_key=True)

class Site(Document):
    """Site"""

    title = StringField(max_length=255, required=True)
```

Raises following error:
    Traceback (most recent call last):
      File "test.py", line 6, in <module>
        class Site(Document):
      File "/usr/local/lib/python2.6/dist-packages/mongoengine/base.py", line 261, in **new**
        raise ValueError('Cannot override primary key field')
    ValueError: Cannot override primary key field

**Comment by hmarr** [comment]
I can't replicate this - what version of MongoEngine / PyMongo are you using?

**Comment by radev** [comment]
MongoEngine 0.3
PyMongo 1.8

**Comment by radev** [comment]
After upgrading to git version 0.4 and pymongo 1.9 this doesn`t happen.
