### ISSUE TITLE
Add a queryset_class property to QuerySetManager

### ISSUE THREAD

**Issue by danjac** [hmarr/mongoengine#89]
The QuerySetManager should have a queryset_class property to allow different queryset classes. At the moment this can only be set for every class, which is somewhat non-DRY.

Even better would be a get_queryset() method, like the one provided with the Django manager.

For example:

```
class CustomQuerySetManager(QuerySetManager):
    queryset_class = MyQuerySet

class MyModel(Document):
     objects = CustomQuerySetManager()

class Post(MyModel):
    pass

class Comment(MyModel):
    pass
```

**Comment by rozza** [comment]
This is fixed in dev

see: https://github.com/hmarr/mongoengine/blob/dev/tests/queryset.py#L1793
and: https://github.com/hmarr/mongoengine/blob/dev/tests/queryset.py#L1817
