### ISSUE TITLE
primary key and collection name

### ISSUE THREAD

**Issue by hrauch** [hmarr/mongoengine#91]
If I use the collection name 'app' and a primary key field, I'm not able to save objects.

Example

class DjaApp(Document):
    name = StringField(required=True, primary_key=True)
    meta = {'collection': 'app'}

a = DjaApp(name='test_01')
a.save()
a = DjaApp(name='test_02')
a.save()
a = DjaApp(name='test_03')
a.save()

Traceback (most recent call last):
  File "import_apps.py", line 140, in <module>
    a.save()
  File "/usr/local/lib/python2.6/dist-packages/mongoengine-0.4-py2.6.egg/mongoengine/document.py", line 85, in save
    raise OperationError(message % unicode(err))
mongoengine.queryset.OperationError: Tried to save duplicate unique keys (E11000 duplicate key error index: djambala_2_db.app.$name_1  dup key: { : null })

If I do the same with a collection name 'apps' or 'app_xxx', everything is fine.

class DjaApp(Document):
    name = StringField(required=True, primary_key=True)
    meta = {'collection': 'apps'}

**Comment by rozza** [comment]
Hi, this is fixed in `dev` branch
