### ISSUE TITLE
Base class for multiple documents

### ISSUE THREAD

**Issue by radev** [hmarr/mongoengine#99]
How I can use base class for multiple documents without it being reflected in the MongoDB?
    "_types" : [ "Document", "Document.Theme" ], "_cls" : "Document.Theme"

I cannot inherit from classes with
    meta = {'allow_inheritance' : False}

**Comment by superbobry** [comment]
I couldn't find anything on the subject in the docs either, it would be great to have `abstract` documents.

**Comment by rozza** [comment]
Abstract documents added in SHA: 088c40f9f2d296f65fd493fd5d98baf02f9125eb

(in dev)
